"""
Canonical decision logic templates per rule family.
MODEL_VERSION: 8.8.0
"""
from __future__ import annotations

from typing import Dict, List, Tuple

MODEL_VERSION = "8.8.0"

# Deterministic rule templates — no AI, no probabilities
_TEMPLATES: Dict[str, Dict[str, object]] = {
    "Beam Discovery": {
        "name": "Official Beam Mark Discovery Coverage",
        "intent": "Ensure every official beam mark is discovered and emitted.",
        "domain": "Annotation Discovery",
        "triggers": (
            "drawing contains beam mark annotation",
            "beam mark matches B### pattern",
        ),
        "inputs": ("annotation_set", "beam_registry"),
        "logic": (
            "IF beam mark annotation exists THEN emit beam_id into production beam set",
            "IF official beam mark absent from production THEN flag Missing Beam Discovery gap",
            "DO NOT invent beam marks not present on drawing",
        ),
        "outputs": ("beam_id", "discovery_status"),
        "validation": (
            "production_beam_set covers official_beam_set for matched drawing scope",
            "no silent drop of valid beam marks",
        ),
        "impl_phase": "Annotation",
        "deps_families": (),
    },
    "Annotation Association": {
        "name": "Production Beam ID Association Filter",
        "intent": "Suppress spurious production beam IDs not present in official model scope.",
        "domain": "Annotation Association",
        "triggers": ("production emits beam_id",),
        "inputs": ("production_beam_ids", "official_beam_ids"),
        "logic": (
            "IF production beam_id not in official/discovered set AND no drawing evidence THEN exclude or quarantine",
            "IF beam_id is alias of discovered mark THEN map via deterministic alias table only when evidence exists",
        ),
        "outputs": ("filtered_beam_ids", "quarantined_beam_ids"),
        "validation": ("extra_beam_count decreases without removing valid beams",),
        "impl_phase": "Annotation",
        "deps_families": ("Beam Discovery",),
    },
    "Role Resolution": {
        "name": "Official Role Family Resolution",
        "intent": "Map reinforcement descriptions to TOP/BOTTOM/STIRRUP/HOOK/SPACER/SFR roles deterministically.",
        "domain": "Engineering Intent",
        "triggers": ("reinforcement annotation or official row description present",),
        "inputs": ("label_text", "layer", "extent", "official_role_synonyms"),
        "logic": (
            "IF description matches top bars-extra THEN role=TOP_EXTRA",
            "IF description matches top bars THEN role=TOP_MAIN",
            "IF description matches bottom bars-extra THEN role=BOTTOM_EXTRA",
            "IF description matches bottom bars THEN role=BOTTOM_MAIN",
            "ELSE apply synonym table; never invent roles",
        ),
        "outputs": ("resolved_role", "role_confidence_flag"),
        "validation": ("official role families have matching production intents/details",),
        "impl_phase": "Intent",
        "deps_families": ("Beam Discovery",),
    },
    "Diameter Resolution": {
        "name": "Diameter Precedence Resolution",
        "intent": "Select diameter consistently from label, dominant bar, and official diameter columns.",
        "domain": "Engineering Intent / Detail",
        "triggers": ("diameter evidence present in label or table",),
        "inputs": ("label_diameter", "candidate_diameters", "official_diameter_kg"),
        "logic": (
            "IF explicit label diameter exists THEN use label diameter",
            "ELSE IF single candidate diameter THEN use candidate",
            "ELSE select diameter with maximum evidence weight; never average diameters",
        ),
        "outputs": ("diameter_mm",),
        "validation": ("diameter-wise steel buckets align within tolerance to official",),
        "impl_phase": "Detail",
        "deps_families": ("Role Resolution",),
    },
    "Stirrup Interpretation": {
        "name": "Multi-Zone Stirrup Interpretation",
        "intent": "Generate Zone A/B/C stirrup pieces from spacing patterns using support-zone logic.",
        "domain": "Reinforcement Detailing",
        "triggers": (
            "beam contains stirrup notation",
            "spacing zones exist OR spacing pattern string present",
        ),
        "inputs": ("stirrup_label", "spacing_pattern", "span_geometry", "support_zones"),
        "logic": (
            "IF stirrup notation exists AND spacing zones exist THEN generate Zone A, Zone B, Zone C",
            "IF single spacing THEN generate one stirrup zone with that spacing",
            "Quantity = deterministic count from zone length / spacing (ceil rules fixed)",
            "DO NOT drop stirrup families when main bars exist",
        ),
        "outputs": ("stirrup_zones", "stirrup_pieces"),
        "validation": ("every official STIRRUP row has >=1 production stirrup piece/bar",),
        "impl_phase": "Detail",
        "deps_families": ("Role Resolution", "Diameter Resolution"),
    },
    "Hook Interpretation": {
        "name": "Stirrup Hook Pairing",
        "intent": "Every stirrup family generates a matching hook family.",
        "domain": "Reinforcement Detailing",
        "triggers": ("stirrup family generated for beam",),
        "inputs": ("stirrup_family", "hook_rules"),
        "logic": (
            "FOR EACH stirrup family THEN generate matching hook family",
            "hook.diameter = stirrup.diameter",
            "hook.quantity = stirrup.quantity",
            "hook.fabrication_zone = stirrup.fabrication_zone",
        ),
        "outputs": ("hook_pieces", "hook_bars"),
        "validation": ("official STIRRUP_HOOK rows covered by paired hooks",),
        "impl_phase": "Detail",
        "deps_families": ("Stirrup Interpretation",),
    },
    "Spacer Interpretation": {
        "name": "Spacer Bar Generation",
        "intent": "Retain spacer-bar intents through detail and piece generation.",
        "domain": "Engineering Intent / Detail",
        "triggers": ("spacer annotation OR official spacer row",),
        "inputs": ("spacer_label", "beam_width", "pin_bar_table"),
        "logic": (
            "IF spacer evidence exists THEN emit SPACER_BAR with diameter/quantity from evidence",
            "DO NOT drop spacers during consolidation",
        ),
        "outputs": ("spacer_bars",),
        "validation": ("official SPACER_BAR rows have production counterparts",),
        "impl_phase": "Intent",
        "deps_families": ("Role Resolution",),
    },
    "Side Face Reinforcement": {
        "name": "Side Face Reinforcement Trigger",
        "intent": "Emit SFR when depth/trigger conditions are met.",
        "domain": "Reinforcement Detailing",
        "triggers": ("beam depth exceeds SFR threshold OR SFR annotation present",),
        "inputs": ("beam_depth", "sfr_threshold", "sfr_annotation"),
        "logic": (
            "IF SFR annotation present OR depth >= threshold THEN emit SIDE_FACE_REINFORCEMENT",
            "Use deterministic diameter/quantity rules from context tables",
        ),
        "outputs": ("sfr_bars",),
        "validation": ("official SFR rows covered when depth/annotation triggers fire",),
        "impl_phase": "Detail",
        "deps_families": ("Role Resolution", "Diameter Resolution"),
    },
    "Cut Length": {
        "name": "Deterministic Cut Length Allocation",
        "intent": "Compute manufacturing cut lengths from geometry without inventing span.",
        "domain": "Piece Generation",
        "triggers": ("piece generation for longitudinal or transverse bars",),
        "inputs": ("span_geometry", "development_length", "hooks", "zone_extents"),
        "logic": (
            "cut_length = geometry-derived length + development/hook allowances per role",
            "NEVER invent span when GeometryProvider lacks data — flag instead",
        ),
        "outputs": ("cut_length_mm",),
        "validation": ("cut lengths within tolerance of official cutting lengths for matched roles",),
        "impl_phase": "Piece",
        "deps_families": ("Role Resolution", "Diameter Resolution"),
    },
    "Steel Aggregation": {
        "name": "EngineeringBar to Steel Total Aggregation",
        "intent": "All EngineeringBars reach diameter and project steel totals.",
        "domain": "Steel Calculation",
        "triggers": ("EngineeringBar set finalized",),
        "inputs": ("engineering_bars", "unit_weights"),
        "logic": (
            "FOR EACH bar: weight = unit_weight(diameter) * total_length * quantity factors",
            "SUM into diameter buckets and project total",
            "DO NOT silently exclude bars from aggregation",
        ),
        "outputs": ("diameter_steel_kg", "project_steel_kg"),
        "validation": ("project steel within tolerance of official TOTAL kg after upstream fixes",),
        "impl_phase": "Steel",
        "deps_families": ("Role Resolution", "Diameter Resolution", "Stirrup Interpretation", "Cut Length"),
    },
    "Weight Calculation": {
        "name": "Unit Weight and Length Reconciliation",
        "intent": "Reconcile unit weights and length×quantity with official kg.",
        "domain": "Steel Calculation",
        "triggers": ("steel weight calculation",),
        "inputs": ("lengths", "diameters", "quantities", "unit_weight_table"),
        "logic": (
            "Use fixed IS unit-weight table",
            "weight = length_m * quantity * unit_weight",
            "Reconcile TOTAL-MT and kg without double counting",
        ),
        "outputs": ("weight_kg",),
        "validation": ("weight totals consistent with aggregated lengths",),
        "impl_phase": "Steel",
        "deps_families": ("Steel Aggregation",),
    },
    "Workbook Mapping": {
        "name": "Workbook Export Completeness",
        "intent": "Ensure workbook export includes all beams, BBS rows, and steel totals.",
        "domain": "Workbook Export",
        "triggers": ("workbook generation",),
        "inputs": ("bbs_rows", "steel_summary", "beam_models"),
        "logic": (
            "Export all beams reaching BBS",
            "Export steel summary consistent with aggregation",
        ),
        "outputs": ("estimation_workbook",),
        "validation": ("workbook exists and totals match steel summary",),
        "impl_phase": "Workbook",
        "deps_families": ("Steel Aggregation",),
    },
    "Piece Generation": {
        "name": "Role-Aligned Piece Expansion",
        "intent": "Expand details into manufacturing pieces aligned with official families.",
        "domain": "Piece Generation",
        "triggers": ("reinforcement detail available",),
        "inputs": ("details", "geometry"),
        "logic": (
            "Expand BOTH_SUPPORTS into L/R pieces",
            "Expand stirrup zones into zone pieces",
            "Preserve role/diameter/quantity",
        ),
        "outputs": ("reinforcement_pieces",),
        "validation": ("piece families cover official reinforcement families",),
        "impl_phase": "Piece",
        "deps_families": ("Role Resolution", "Stirrup Interpretation", "Hook Interpretation"),
    },
    "Future": {
        "name": "Future Unsupported Case Placeholder",
        "intent": "Capture unsupported cases for future rule authoring.",
        "domain": "Future",
        "triggers": ("unclassified engineering issue",),
        "inputs": ("issue_evidence",),
        "logic": ("RECORD evidence; DO NOT auto-correct",),
        "outputs": ("future_rule_candidate",),
        "validation": ("placeholder only",),
        "impl_phase": "Future",
        "deps_families": (),
    },
}


def template_for(family: str) -> Dict[str, object]:
    return _TEMPLATES.get(family, _TEMPLATES["Future"])
