"""W.11 timeout and progress constants. No secrets."""
from __future__ import annotations

PHASE_ID = "W.11"
PHASE_NAME = "Hybrid Production Reliability"
GATE_VERSION = "W11_HYBRID_RELIABILITY_V1"

PROGRESS_FILENAME = "hybrid_progress.json"
LIFECYCLE_FILENAME = "hybrid_lifecycle.json"

# Defaults chosen from W.9/W.10 measured Vision (~11 s/beam) and the W.11
# stuck-run evidence (~25 s/beam P2.6.10 render on a large drawing).
DEFAULT_PER_CALL_TIMEOUT_S = 120.0
DEFAULT_MAX_RETRIES = 1
DEFAULT_TOTAL_BEAM_TIMEOUT_S = 250.0
DEFAULT_EVIDENCE_TIMEOUT_S = 120.0
DEFAULT_STALE_PROGRESS_S = 180.0

PHASE_EVIDENCE = "EVIDENCE_GENERATION"
PHASE_VISION = "CLAUDE_VISION"
PHASE_RESOLUTION = "SEMANTIC_RESOLUTION"
PHASE_COMPLETE = "HYBRID_COMPLETE"
PHASE_FALLBACK = "DETERMINISTIC_FALLBACK"

STATUS_VISION_TIMEOUT = "VISION_TIMEOUT"
STATUS_VISION_API_ERROR = "VISION_API_ERROR"
STATUS_VISION_RETRY_EXHAUSTED = "VISION_RETRY_EXHAUSTED"
STATUS_EVIDENCE_TIMEOUT = "EVIDENCE_TIMEOUT"
STATUS_EVIDENCE_ERROR = "EVIDENCE_ERROR"
