"""Engineering Semantic Role type constants — bridge between geometry and objects."""

from __future__ import annotations

from typing import FrozenSet

ROLE_UNKNOWN = "UNKNOWN_ROLE"
ROLE_LONGITUDINAL = "LONGITUDINAL_REINFORCEMENT_ROLE"
ROLE_TRANSVERSE = "TRANSVERSE_REINFORCEMENT_ROLE"
ROLE_SIDE_FACE = "SIDE_FACE_REINFORCEMENT_ROLE"
ROLE_SPACER = "SPACER_ROLE"
ROLE_DEVELOPMENT_LENGTH = "DEVELOPMENT_LENGTH_ROLE"
ROLE_DIMENSION = "DIMENSION_ROLE"
ROLE_BEAM_IDENTIFIER = "BEAM_IDENTIFIER_ROLE"
ROLE_HOOK = "HOOK_ROLE"
ROLE_ANCHORAGE = "ANCHORAGE_ROLE"
ROLE_GENERAL_NOTE = "GENERAL_NOTE_ROLE"
ROLE_SECTION_IDENTIFIER = "SECTION_IDENTIFIER_ROLE"
ROLE_LEADER = "LEADER_ROLE"
ROLE_CALLOUT = "CALLOUT_ROLE"

VALID_SEMANTIC_ROLE_TYPES: FrozenSet[str] = frozenset({
    ROLE_UNKNOWN,
    ROLE_LONGITUDINAL,
    ROLE_TRANSVERSE,
    ROLE_SIDE_FACE,
    ROLE_SPACER,
    ROLE_DEVELOPMENT_LENGTH,
    ROLE_DIMENSION,
    ROLE_BEAM_IDENTIFIER,
    ROLE_HOOK,
    ROLE_ANCHORAGE,
    ROLE_GENERAL_NOTE,
    ROLE_SECTION_IDENTIFIER,
    ROLE_LEADER,
    ROLE_CALLOUT,
})

CLASSIFICATION_SOURCE_GEOMETRY = "GEOMETRY"
CLASSIFICATION_SOURCE_TEXT = "TEXT"
CLASSIFICATION_SOURCE_LEADER = "LEADER"
CLASSIFICATION_SOURCE_BLOCK = "BLOCK"
CLASSIFICATION_SOURCE_RELATIONSHIP = "RELATIONSHIP"
CLASSIFICATION_SOURCE_GEOMETRY_AND_TEXT = "GEOMETRY_AND_TEXT"

PRIORITY_CRITICAL = "CRITICAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"
PRIORITY_UNKNOWN = "UNKNOWN"

VALID_ENGINEERING_PRIORITIES: FrozenSet[str] = frozenset({
    PRIORITY_CRITICAL,
    PRIORITY_HIGH,
    PRIORITY_MEDIUM,
    PRIORITY_LOW,
    PRIORITY_UNKNOWN,
})

ROLE_ENGINEERING_PRIORITY: dict[str, str] = {
    ROLE_UNKNOWN: PRIORITY_UNKNOWN,
    ROLE_LONGITUDINAL: PRIORITY_CRITICAL,
    ROLE_TRANSVERSE: PRIORITY_CRITICAL,
    ROLE_SIDE_FACE: PRIORITY_HIGH,
    ROLE_SPACER: PRIORITY_MEDIUM,
    ROLE_DEVELOPMENT_LENGTH: PRIORITY_HIGH,
    ROLE_DIMENSION: PRIORITY_HIGH,
    ROLE_BEAM_IDENTIFIER: PRIORITY_CRITICAL,
    ROLE_HOOK: PRIORITY_MEDIUM,
    ROLE_ANCHORAGE: PRIORITY_MEDIUM,
    ROLE_GENERAL_NOTE: PRIORITY_LOW,
    ROLE_SECTION_IDENTIFIER: PRIORITY_MEDIUM,
    ROLE_LEADER: PRIORITY_MEDIUM,
    ROLE_CALLOUT: PRIORITY_LOW,
}


def priority_for_role_type(role_type: str) -> str:
    return ROLE_ENGINEERING_PRIORITY.get(role_type, PRIORITY_UNKNOWN)
