"""
P W.5 — Production Hybrid Shadow Adapter.
SHADOW ONLY. No production Excel writes. Authoritative mode is defined but forbidden.
"""
from __future__ import annotations

MODEL_VERSION = "10.0.0"
PHASE_ID = "W.5"
PHASE_NAME = "Production Hybrid Shadow Adapter"
OUTPUT_DIRNAME = "PhaseW5_production_hybrid_shadow"
GATE_VERSION = "W5_PRODUCTION_HYBRID_SHADOW_V1"

PRODUCTION_WRITE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"
ENGINEERING_CHANGES = "NONE"
AUTHORITATIVE_ENABLED = False

MODE_OFF = "off"
MODE_SHADOW = "shadow"
MODE_PRODUCTION = "production"
MODE_AUTHORITATIVE = "authoritative"
ALLOWED_MODES = (MODE_OFF, MODE_SHADOW, MODE_PRODUCTION, MODE_AUTHORITATIVE)

ENV_HYBRID_MODE = "HYBRID_MODE"
ENV_API_KEY = "ANTHROPIC_API_KEY"
ENV_MODEL = "HYBRID_CLAUDE_MODEL"
ENV_MAX_LIVE_CALLS = "HYBRID_MAX_LIVE_CALLS"
ENV_MAX_WALL_S = "HYBRID_MAX_WALL_S"
ENV_PER_CALL_TIMEOUT_S = "HYBRID_PER_CALL_TIMEOUT_S"
ENV_MAX_RETRIES = "HYBRID_MAX_RETRIES"
ENV_TOTAL_BEAM_TIMEOUT_S = "HYBRID_TOTAL_BEAM_TIMEOUT_SECONDS"
ENV_EVIDENCE_TIMEOUT_S = "HYBRID_EVIDENCE_TIMEOUT_SECONDS"
ENV_DOTENV_PATH = "ANTHROPIC_DOTENV_PATH"

DEFAULT_MAX_LIVE_CALLS = 6
DEFAULT_MAX_WALL_S = 90.0
DEFAULT_PER_CALL_TIMEOUT_S = 120.0
DEFAULT_MAX_RETRIES = 1
DEFAULT_TOTAL_BEAM_TIMEOUT_S = 250.0
DEFAULT_EVIDENCE_TIMEOUT_S = 120.0
MIN_RENDER_BYTES = 200

T1_RENDER_REL = "data/output/PhaseT1_geometric_stirrup_evidence/opencv_renders"
R13_REL = "data/output/PhaseR1.3_pipeline_integration/beam_reinforcement_models_production.json"
EXCEL_REL = "data/output/Production_Output/Estimation_Output.xlsx"
STEEL_SUMMARY_REL = "data/output/Production_Output/steel_weight_summary.json"

VISUAL_SOURCE = "T1_OPENCV_CROP"

# ESTIMATED public list prices (USD per million tokens). Never treat as billed exact.
ESTIMATED_INPUT_USD_PER_MTOK = 3.00
ESTIMATED_OUTPUT_USD_PER_MTOK = 15.00
COST_BASIS = "ESTIMATED"

AGREE = "AGREE"
BENIGN_DIFFERENCE = "BENIGN_DIFFERENCE"
SEMANTIC_DISAGREEMENT = "SEMANTIC_DISAGREEMENT"
MATERIAL_DISAGREEMENT = "MATERIAL_DISAGREEMENT"
HYBRID_UNAVAILABLE = "HYBRID_UNAVAILABLE"
HYBRID_ERROR = "HYBRID_ERROR"

STATUS_SKIPPED_OFF = "SKIPPED_MODE_OFF"
STATUS_AUTHORITATIVE_FORBIDDEN = "AUTHORITATIVE_FORBIDDEN"
STATUS_KEY_ABSENT = "KEY_ABSENT"
STATUS_NO_ENGINEERING = "NO_ENGINEERING_CONTEXT"
STATUS_COMPLETE = "COMPLETE"
STATUS_PARTIAL_BUDGET = "PARTIAL_BUDGET"
STATUS_ERROR = "ERROR"
STATUS_DISABLED_UNAVAILABLE = "HYBRID_UNAVAILABLE"
