"""
Phase P2.6.4 — Selective XOR / Role-Gap Refinement.
MODEL_VERSION: 10.11.4

Shadow / research only. Deterministic production remains sole authority.
No engineering recompute. No production insert.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.4"
PHASE_ID = "P2.6.4"
PHASE_NAME = "Selective XOR / Role-Gap Refinement"
OUTPUT_DIRNAME = "PhaseP264_selective_role_gap_gate"
SCOPE = "FROZEN_P261_STRATIFIED_SAMPLE"
MODE = "GATE_SHADOW"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P264_SELECTIVE_ROLE_GAP_GATE_V1_0"
P263_GATE_VERSION = "P263_LONGITUDINAL_AWARE_GATE_V1_0"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

SAMPLE_SEED = 2611101
FROZEN_SAMPLE_BEAMS = 75
MAX_LIVE_CALLS = 0

MODE_REPLAY = "REPLAY_P261_CACHED"
MODE_LIVE = "LIVE_API"

P261_OUTPUT_DIRNAME = "PhaseP261_stratified_vision_candidate_recovery"
P262_OUTPUT_DIRNAME = "PhaseP262_selective_vision_candidate_gate"
P263_OUTPUT_DIRNAME = "PhaseP263_longitudinal_aware_gate"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"
DECISION_HOLD = "HOLD"

PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"

CALL_REASONS = (
    "STIRRUP_TEXT_NO_OBJECT",
    "OCR_CORRUPTED_STIRRUP",
    "INCOMPLETE_PARSE",
    "UNASSOCIATED_REINFORCEMENT",
    "MISSING_DETERMINISTIC_OBJECT",
    "LONGITUDINAL_COVERAGE_SHORTFALL",
    "LONGITUDINAL_SEMANTIC_CONFLICT",
    "OTHER",
)
SKIP_REASONS = (
    "MATCHING_OBJECT_EXISTS",
    "COMPLETE_PARSE",
    "NO_PRODUCTION_GAP",
    "STRONG_DETERMINISTIC_COVERAGE",
    "LONGITUDINAL_FULLY_COVERED",
    "ROLE_GAP_DETERMINISTICALLY_EXPLAINED",
)

COVER_FULL = "FULLY_COVERED"
COVER_QTY = "QUANTITY_SHORTFALL"
COVER_ROLE = "ROLE_CONFLICT"
COVER_DIA = "DIAMETER_CONFLICT"
COVER_MULTI = "MULTIPLE_CALLOUT_SHORTFALL"
COVER_MISSING = "MISSING_OBJECT"
COVER_LAYER = "ROLE_COVERAGE_GAP"
COVER_UNASSOC = "UNASSOCIATED"
COVER_NONE = "NO_LONGITUDINAL_DEMAND"
COVER_UNCERTAIN = "UNCERTAIN"

ROLE_GAP_REQUIRED = "ROLE_GAP_REQUIRES_VISION"
ROLE_GAP_EXPLAINED = "ROLE_GAP_DETERMINISTICALLY_EXPLAINED"
ROLE_GAP_NA = "ROLE_GAP_NOT_APPLICABLE"

DET_ALREADY = "ALREADY_DETECTED"

STRATA = ("DIFFICULT", "NORMAL", "EASY")
TYPE_GROUPS = (
    "STIRRUP",
    "LONGITUDINAL_REINFORCEMENT",
    "SIDE_FACE_REINFORCEMENT",
    "OTHER",
)

P263_BASELINE = {
    "CALL_BEAMS": 40,
    "SKIP_BEAMS": 35,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.466667,
    "GATED_VISION_CANDIDATES": 108,
    "DUPLICATE_RATE_GATED": 0.50,
    "GATED_PRECISION": 0.685185,
    "GATED_UNSUPPORTED_RATE": 0.101852,
    "GATED_TRUE_RECOVERIES": 25,
    "RECOVERY_RETENTION_RATE": 0.961538,
    "FALSE_SKIPS": 1,
    "FALSE_CALLS": 16,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 62.5,
    "STIRRUP_RETAINED": 18,
    "LONGITUDINAL_RETAINED": 7,
    "ROLE_COVERAGE_GAP_BEAMS": 18,
}

P262_BASELINE = {
    "CALL_BEAMS": 38,
    "SKIP_BEAMS": 37,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.493333,
    "GATED_VISION_CANDIDATES": 118,
    "DUPLICATE_RATE_GATED": 0.533898,
    "GATED_PRECISION": 0.711864,
    "GATED_UNSUPPORTED_RATE": 0.09322,
    "GATED_TRUE_RECOVERIES": 22,
    "RECOVERY_RETENTION_RATE": 0.846154,
    "FALSE_SKIPS": 4,
    "FALSE_CALLS": 17,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 57.8947,
    "STIRRUP_RETAINED": 18,
    "LONGITUDINAL_RETAINED": 4,
}
