"""
Excel Structure Builder — Phase V.B.1 MODULE 4

Defines the estimator workbook layout:
  - Worksheet names, headers, column order, engineering grouping
Matches the reference estimator workbook structure as closely as possible.
"""
from dataclasses import dataclass, field
from typing import List, Tuple, Optional

# ── Worksheet names (matching estimator) ────────────────────────────────────
WS_PROJECT_HEADER = "Project Header"
WS_GENERAL_NOTES  = "General Notes"
WS_BEAM_SUMMARY   = "Beam Summary"
WS_BBS            = "Bar Bending Schedule"
WS_STEEL_SUMMARY  = "Steel Summary"
WS_DIAM_SUMMARY   = "Diameter Summary"
WS_PROJECT_TOTALS = "Project Totals"

ALL_WORKSHEETS = [
    WS_PROJECT_HEADER,
    WS_GENERAL_NOTES,
    WS_BEAM_SUMMARY,
    WS_BBS,
    WS_STEEL_SUMMARY,
    WS_DIAM_SUMMARY,
    WS_PROJECT_TOTALS,
]

# ── Column definitions ───────────────────────────────────────────────────────
# BBS columns (matching estimator BBS sheet column order)
BBS_COLUMNS: List[Tuple[str, str, float]] = [
    # (header text, attribute_key, column_width)
    ("SI No",                "si_no",            6),
    ("Frame",                "frame_type",        6),
    ("Description",          "description",      20),
    ("Dia (mm)",             "diameter_mm",       8),
    ("Spacing (m)",          "spacing_m",         9),
    ("No. of Bars",          "quantity",          9),
    ("Dvlp. L (m)",          "dvlp_length_m",    10),
    ("Cut Length (m)",       "cut_length_m",     12),
    ("Total Length (m)",     "total_length_m",   12),
    ("Y8 (kg)",              "weight_d8",        10),
    ("Y10 (kg)",             "weight_d10",       10),
    ("Y12 (kg)",             "weight_d12",       10),
    ("Y16 (kg)",             "weight_d16",       10),
    ("Y20 (kg)",             "weight_d20",       10),
    ("Y25 (kg)",             "weight_d25",       10),
    ("Y32 (kg)",             "weight_d32",       10),
    ("Total (kg)",           "total_weight_kg",  12),
]

# Beam summary columns
BEAM_SUMMARY_COLUMNS: List[Tuple[str, float]] = [
    ("Beam ID",             14),
    ("Span (m)",            10),
    ("Width (m)",           10),
    ("Depth (m)",           10),
    ("Total Bars",          10),
    ("Steel Weight (kg)",   16),
    ("Y8 (kg)",             10),
    ("Y10 (kg)",            10),
    ("Y12 (kg)",            10),
    ("Y16 (kg)",            10),
    ("Y20 (kg)",            10),
    ("Y25 (kg)",            10),
    ("Y32 (kg)",            10),
]

# Diameter summary columns
DIAM_SUMMARY_COLUMNS: List[Tuple[str, float]] = [
    ("Diameter (mm)",       14),
    ("Total Bars",          12),
    ("Total Length (mm)",   16),
    ("Total Weight (kg)",   16),
    ("Weight Fraction (%)", 18),
]

# Steel summary columns (per beam per diameter)
STEEL_SUMMARY_COLUMNS: List[Tuple[str, float]] = [
    ("Beam ID",     14),
    ("Y8 (kg)",     10),
    ("Y10 (kg)",    10),
    ("Y12 (kg)",    10),
    ("Y16 (kg)",    10),
    ("Y20 (kg)",    10),
    ("Y25 (kg)",    10),
    ("Y32 (kg)",    10),
    ("Total (kg)",  12),
]

# Project totals columns
PROJECT_TOTALS_COLUMNS: List[Tuple[str, float]] = [
    ("Item",              24),
    ("Value",             18),
    ("Unit",              12),
]


# ── Project metadata ─────────────────────────────────────────────────────────
PROJECT_HEADER_DATA = {
    "Project Title":     "SHR & OHT Top Framing Panel",
    "Drawing Reference": "Galera Estimation — Benchmark Set 1",
    "Concrete Grade":    "C25/30",
    "Steel Grade":       "Fe415 (High Yield)",
    "Cover (mm)":        "40",
    "Generated By":      "V6.6.0 Production Output Engine",
    "Standard":          "IS 456:2000 / IS 2502:1963",
}

GENERAL_NOTES = [
    "1. All dimensions are in mm unless otherwise stated.",
    "2. Development length = 40d (IS 456:2000, Fe415, M25).",
    "3. Stirrup hook allowance = 2 x 10d (135-degree hook).",
    "4. Clear cover = 40 mm (IS 456:2000 Table 16).",
    "5. Steel density = 7850 kg/m³.",
    "6. Cut length = clear span + 2 x development length (main bars).",
    "7. Stirrup cut length = 2(W-2c) + 2(D-2c) + 2x10d.",
    "8. Y = High Yield Deformed bars (Fe415).",
    "9. This schedule is for engineering review and manual verification.",
    "10. Phase V.B.1 — Production Output Completion (MODEL_VERSION 6.6.0).",
]


def build_project_header_data(loader_summary: dict = None) -> dict:
    """Build project header from EngineeringContext when available."""
    if not loader_summary:
        return dict(PROJECT_HEADER_DATA)
    sg = loader_summary.get("primary_steel_grade", "Fe415")
    cg = loader_summary.get("concrete_grade_beam", "M30")
    cover = loader_summary.get("cover_beam_mm", 40)
    return {
        "Project Title":     "SHR & OHT Top Framing Panel",
        "Drawing Reference": "Galera Estimation — Benchmark Set 2",
        "Concrete Grade":    cg,
        "Steel Grade":       f"{sg} (High Yield)",
        "Cover (mm)":        str(cover),
        "Generated By":      "V7.6.0 Production Output Engine (R.2B)",
        "Standard":          "IS 456:2000 / IS 2502:1963",
    }


def build_general_notes(loader_summary: dict = None) -> list:
    """Build general notes from EngineeringContext when available."""
    if not loader_summary:
        return list(GENERAL_NOTES)
    sg = loader_summary.get("primary_steel_grade", "Fe415")
    cg = loader_summary.get("concrete_grade_beam", "M30")
    cover = loader_summary.get("cover_beam_mm", 40)
    dl_factor = loader_summary.get("dev_length_factor", 40)
    hook = loader_summary.get("hook_multiple_135", 10)
    density = loader_summary.get("steel_density", 7850)
    min_lap = loader_summary.get("min_lap_mm", 300)
    return [
        "1. All dimensions are in mm unless otherwise stated.",
        f"2. Development length from GN DXF table ({sg}, {cg}) — factor ~{dl_factor}d for dia=12.",
        f"3. Stirrup hook allowance = 2 x {hook}d (135-degree hook, from GN DXF).",
        f"4. Clear cover = {cover} mm (from GN DXF TABLE 2).",
        f"5. Steel density = {density} kg/m³.",
        "6. Cut length = clear span + 2 x development length (main bars).",
        f"7. Stirrup cut length = 2(W-2c) + 2(D-2c) + 2x{hook}d.",
        f"8. Y = High Yield Deformed bars ({sg}).",
        f"9. Minimum lap splice = {min_lap} mm (from GN DXF).",
        "10. Phase R.2B — Engineering Context Consumption (MODEL_VERSION 7.6.0).",
    ]
