"""
Phase P2.6.1 — Stratified Vision Candidate Recovery Benchmark.
MODEL_VERSION: 10.11.1

Shadow / research only. Deterministic production remains sole authority.
No engineering recompute. No production insert.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.1"
PHASE_ID = "P2.6.1"
PHASE_NAME = "Stratified Vision Candidate Recovery Benchmark"
OUTPUT_DIRNAME = "PhaseP261_stratified_vision_candidate_recovery"
SCOPE = "STRATIFIED_SAMPLE_FOURTH_FIFTH_SIXTH"
MODE = "BENCHMARK_SHADOW"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "SHADOW_CANDIDATE_RECOVERY"

PROMPT_VERSION = "P261_NEUTRAL_VISION_CANDIDATE_PROMPT_V1"
SCHEMA_VERSION = "P26_VISION_CANDIDATE_SCHEMA_V1"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

TARGET_BEAMS = 75
PER_STRATUM = 25
MAX_LIVE_CALLS = 90
SAMPLE_SEED = 2611101

MODE_CACHE_ONLY = "CACHE_ONLY"
MODE_LIVE_API = "LIVE_API"

SET_KEYS = ("Fourth", "Fifth", "Sixth")
STRATA = ("DIFFICULT", "NORMAL", "EASY")

CROP_SOURCE = "QA30_SHARED_RENDER"
CROP_BASE_MARGIN_MM = 250.0
CROP_EVIDENCE_PAD_MM = 120.0
CROP_RENDER_MAX_DIM_PX = 1200

INPUT_USD_PER_MTOK = 3.0
OUTPUT_USD_PER_MTOK = 15.0

DECISION_SHADOW = "SHADOW_CANDIDATE"

DET_ALREADY = "ALREADY_DETECTED"
DET_MISSING = "POTENTIALLY_MISSING"
DET_CONFLICT = "CONFLICTING"
DET_AMBIGUOUS = "AMBIGUOUS"
DET_UNKNOWN = "UNKNOWN"

GT_MATCH = "GT_MATCH"
GT_TRUE_RECOVERY = "TRUE_RECOVERY"
GT_DUPLICATE = "DUPLICATE"
GT_UNSUPPORTED = "UNSUPPORTED"
GT_AMBIGUOUS = "AMBIGUOUS"

P26_PILOT_BEAMS = frozenset(
    {
        "B130", "B128", "B129", "B137", "B142", "B147", "B168", "B181",
        "B46", "B47", "B63", "B81", "B82", "B43", "B62", "B139", "B141", "B144",
    }
)
