"""Property candidate type constants — Phase G.5.2."""

from __future__ import annotations

from typing import FrozenSet

CANDIDATE_DIAMETER = "DIAMETER"
CANDIDATE_QUANTITY = "QUANTITY"
CANDIDATE_SPACING = "SPACING"
CANDIDATE_BAR_MARK = "BAR_MARK"
CANDIDATE_BAR_TYPE = "BAR_TYPE"
CANDIDATE_REINFORCEMENT_CODE = "REINFORCEMENT_CODE"
CANDIDATE_HOOK = "HOOK"
CANDIDATE_HOOK_DIRECTION = "HOOK_DIRECTION"
CANDIDATE_BEND = "BEND"
CANDIDATE_LAP = "LAP"
CANDIDATE_DEVELOPMENT_LENGTH = "DEVELOPMENT_LENGTH"
CANDIDATE_ANCHORAGE = "ANCHORAGE"
CANDIDATE_CUT_LENGTH = "CUT_LENGTH"
CANDIDATE_BAR_LENGTH = "BAR_LENGTH"
CANDIDATE_SHAPE_CODE = "SHAPE_CODE"
CANDIDATE_BAR_LOCATION = "BAR_LOCATION"
CANDIDATE_START_OFFSET = "START_OFFSET"
CANDIDATE_END_OFFSET = "END_OFFSET"
CANDIDATE_ZONE = "ZONE"
CANDIDATE_LEVEL = "LEVEL"
CANDIDATE_MARK = "MARK"
CANDIDATE_NOTE = "NOTE"
CANDIDATE_TEXT = "TEXT"
CANDIDATE_DIMENSION = "DIMENSION"
CANDIDATE_LEADER = "LEADER"
CANDIDATE_SKETCH = "SKETCH"
CANDIDATE_BLOCK = "BLOCK"
CANDIDATE_CALLOUT = "CALLOUT"
CANDIDATE_UNKNOWN = "UNKNOWN"

VALID_CANDIDATE_TYPES: FrozenSet[str] = frozenset({
    CANDIDATE_DIAMETER,
    CANDIDATE_QUANTITY,
    CANDIDATE_SPACING,
    CANDIDATE_BAR_MARK,
    CANDIDATE_BAR_TYPE,
    CANDIDATE_REINFORCEMENT_CODE,
    CANDIDATE_HOOK,
    CANDIDATE_HOOK_DIRECTION,
    CANDIDATE_BEND,
    CANDIDATE_LAP,
    CANDIDATE_DEVELOPMENT_LENGTH,
    CANDIDATE_ANCHORAGE,
    CANDIDATE_CUT_LENGTH,
    CANDIDATE_BAR_LENGTH,
    CANDIDATE_SHAPE_CODE,
    CANDIDATE_BAR_LOCATION,
    CANDIDATE_START_OFFSET,
    CANDIDATE_END_OFFSET,
    CANDIDATE_ZONE,
    CANDIDATE_LEVEL,
    CANDIDATE_MARK,
    CANDIDATE_NOTE,
    CANDIDATE_TEXT,
    CANDIDATE_DIMENSION,
    CANDIDATE_LEADER,
    CANDIDATE_SKETCH,
    CANDIDATE_BLOCK,
    CANDIDATE_CALLOUT,
    CANDIDATE_UNKNOWN,
})

SOURCE_TYPE_TEXT = "TEXT"
SOURCE_TYPE_LEADER = "LEADER"
SOURCE_TYPE_DIMENSION = "DIMENSION"
SOURCE_TYPE_SKETCH = "SKETCH"
SOURCE_TYPE_BLOCK = "BLOCK"
SOURCE_TYPE_CALLOUT = "CALLOUT"
SOURCE_TYPE_NOTE = "NOTE"
SOURCE_TYPE_UNKNOWN = "UNKNOWN"

VALID_SOURCE_TYPES: FrozenSet[str] = frozenset({
    SOURCE_TYPE_TEXT,
    SOURCE_TYPE_LEADER,
    SOURCE_TYPE_DIMENSION,
    SOURCE_TYPE_SKETCH,
    SOURCE_TYPE_BLOCK,
    SOURCE_TYPE_CALLOUT,
    SOURCE_TYPE_NOTE,
    SOURCE_TYPE_UNKNOWN,
})

DISCOVERY_DIRECT = "DIRECT_RELATIONSHIP"
DISCOVERY_ONE_HOP = "ONE_HOP"
DISCOVERY_TWO_HOP = "TWO_HOP"
DISCOVERY_ANNOTATION_CHAIN = "ANNOTATION_CHAIN"
DISCOVERY_LEADER_CHAIN = "LEADER_CHAIN"
DISCOVERY_TEXT_CHAIN = "TEXT_CHAIN"
DISCOVERY_CALLOUT_CHAIN = "CALLOUT_CHAIN"
DISCOVERY_GRAPH_INFERENCE = "GRAPH_INFERENCE"
DISCOVERY_UNKNOWN = "UNKNOWN"

VALID_DISCOVERY_METHODS: FrozenSet[str] = frozenset({
    DISCOVERY_DIRECT,
    DISCOVERY_ONE_HOP,
    DISCOVERY_TWO_HOP,
    DISCOVERY_ANNOTATION_CHAIN,
    DISCOVERY_LEADER_CHAIN,
    DISCOVERY_TEXT_CHAIN,
    DISCOVERY_CALLOUT_CHAIN,
    DISCOVERY_GRAPH_INFERENCE,
    DISCOVERY_UNKNOWN,
})

STATUS_DISCOVERED = "DISCOVERED"
STATUS_REGISTERED = "CANDIDATE_REGISTERED"

VALID_CANDIDATE_STATUSES: FrozenSet[str] = frozenset({
    STATUS_DISCOVERED,
    STATUS_REGISTERED,
})

CREATED_PHASE = "G.5.2"

MAX_TRAVERSAL_DISTANCE = 3

CONFIDENCE_DIRECT = 0.95
CONFIDENCE_ONE_HOP = 0.90
CONFIDENCE_TWO_HOP = 0.82
CONFIDENCE_GENERAL_NOTE = 0.70
CONFIDENCE_UNKNOWN = 0.40
