"""Engineering Specification type constants — Phase H.1."""

from __future__ import annotations

from typing import Dict, FrozenSet

from src.engineering_specifications.specification_field_contract import (
    FORBIDDEN_SPECIFICATION_EMBEDDED_FIELDS,
)

SPEC_TOP_MAIN_REINFORCEMENT = "TOP_MAIN_REINFORCEMENT"
SPEC_BOTTOM_MAIN_REINFORCEMENT = "BOTTOM_MAIN_REINFORCEMENT"
SPEC_EXTRA_TOP_REINFORCEMENT = "EXTRA_TOP_REINFORCEMENT"
SPEC_EXTRA_BOTTOM_REINFORCEMENT = "EXTRA_BOTTOM_REINFORCEMENT"
SPEC_STIRRUP = "STIRRUP"
SPEC_LINK = "LINK"
SPEC_HAUNCH_BAR = "HAUNCH_BAR"
SPEC_EDGE_BAR = "EDGE_BAR"
SPEC_STARTER_BAR = "STARTER_BAR"
SPEC_UNKNOWN = "UNKNOWN"

VALID_SPECIFICATION_TYPES: FrozenSet[str] = frozenset({
    SPEC_TOP_MAIN_REINFORCEMENT,
    SPEC_BOTTOM_MAIN_REINFORCEMENT,
    SPEC_EXTRA_TOP_REINFORCEMENT,
    SPEC_EXTRA_BOTTOM_REINFORCEMENT,
    SPEC_STIRRUP,
    SPEC_LINK,
    SPEC_HAUNCH_BAR,
    SPEC_EDGE_BAR,
    SPEC_STARTER_BAR,
    SPEC_UNKNOWN,
})

STATUS_COMPLETE = "COMPLETE"
STATUS_PARTIAL = "PARTIAL"
STATUS_CONFLICT = "CONFLICT"
STATUS_DEFERRED = "DEFERRED"

VALID_SPECIFICATION_STATUSES: FrozenSet[str] = frozenset({
    STATUS_COMPLETE,
    STATUS_PARTIAL,
    STATUS_CONFLICT,
    STATUS_DEFERRED,
})

PREFIX_SPECIFICATION = "SPEC"
PREFIX_SPECIFICATION_REGISTRY = "SPEC_REGISTRY"

CREATED_PHASE = "H.1"

OBJECT_TYPE_TO_SPECIFICATION_TYPE: Dict[str, str] = {
    "TOP_REINFORCEMENT": SPEC_TOP_MAIN_REINFORCEMENT,
    "TOP_BAR": SPEC_TOP_MAIN_REINFORCEMENT,
    "TOP_EXTRA_BAR": SPEC_EXTRA_TOP_REINFORCEMENT,
    "BOTTOM_REINFORCEMENT": SPEC_BOTTOM_MAIN_REINFORCEMENT,
    "BOTTOM_BAR": SPEC_BOTTOM_MAIN_REINFORCEMENT,
    "BOTTOM_EXTRA_BAR": SPEC_EXTRA_BOTTOM_REINFORCEMENT,
    "STIRRUP": SPEC_STIRRUP,
    "SPACER_BAR": SPEC_LINK,
    "SIDE_FACE_REINFORCEMENT": SPEC_EDGE_BAR,
    "HAUNCH_BAR": SPEC_HAUNCH_BAR,
    "STARTER_BAR": SPEC_STARTER_BAR,
    "LINK": SPEC_LINK,
    "UNKNOWN_OBJECT": SPEC_UNKNOWN,
    "UNKNOWN": SPEC_UNKNOWN,
}

SPECIFICATION_ELIGIBLE_OBJECT_TYPES: FrozenSet[str] = frozenset(
    OBJECT_TYPE_TO_SPECIFICATION_TYPE.keys()
)

PROPERTY_TYPE_TO_SPEC_FIELD: Dict[str, str] = {
    "QUANTITY": "quantity",
    "DIAMETER": "diameter",
    "BAR_TYPE": "bar_type",
    "SPACING": "spacing",
    "BAR_MARK": "bar_mark",
    "SHAPE_CODE": "shape_code",
    "HOOK": "hook",
    "HOOK_DIRECTION": "hook_direction",
    "LEVEL": "level",
    "ZONE": "zone",
    "CALLOUT": "callout",
    "NOTES": "notes",
    "REINFORCEMENT_CODE": "callout",
    "LOCATION": "zone",
}

FORBIDDEN_SPECIFICATION_FIELDS: FrozenSet[str] = FORBIDDEN_SPECIFICATION_EMBEDDED_FIELDS

DEFERRED_PROPERTY_TYPES: FrozenSet[str] = frozenset({
    "BAR_LENGTH",
    "CUT_LENGTH",
    "DEVELOPMENT_LENGTH",
    "LAP_LENGTH",
    "ANCHORAGE",
    "CURTAILMENT",
    "BAR_LOCATION",
    "BEND",
    "OFFSET",
})
