"""Static inventory of existing Version10 render/crop components. Discovery only."""
from __future__ import annotations

from typing import Any, Dict, List

DISCOVERED_COMPONENTS: List[Dict[str, Any]] = [
    {
        "file": "Version10/src/PhaseM.1_engineering_vision_dataset/dxf_renderer.py",
        "class_function": "render_dxf_region_to_png / render_dxf_to_png / CoordTransform",
        "purpose": "Canonical ezdxf+matplotlib PNG renderer for a caller-supplied DXF extent",
        "rendering_method": "ezdxf Frontend + MatplotlibBackend (Agg) PNG",
        "localization_method": "none (extent is caller-supplied)",
        "dependencies": "ezdxf, matplotlib, optional PIL",
        "supports_dxf_directly": True,
        "can_isolate_beam": "IF_CALLER_SUPPLIES_EXTENT",
        "uses_beam_geometry": False,
        "uses_beam_title": False,
        "uses_annotation_association": False,
        "output_formats": ["PNG"],
        "coordinate_system": "DXF Y-up, image Y-down via CoordTransform",
        "existing_tests": "M.1 / T1.1 renderer validation",
        "known_limitations": "No SVG/PDF/ODA. Does not locate beams by itself.",
        "independence": "INDEPENDENT",
        "reuse": "YES",
    },
    {
        "file": "Version10/src/PhaseM.1_engineering_vision_dataset/beam_cropper.py",
        "class_function": "compute_beam_dxf_bbox / crop_beam_image",
        "purpose": "Coarse centroid window from BeamAxis/registry",
        "rendering_method": "pixel crop of a full-sheet PNG",
        "localization_method": "beam geometry/registry centroid ±3000 mm",
        "dependencies": "beam registry / axis",
        "supports_dxf_directly": False,
        "can_isolate_beam": "COARSE",
        "uses_beam_geometry": True,
        "uses_beam_title": False,
        "uses_annotation_association": False,
        "output_formats": ["PNG"],
        "coordinate_system": "DXF bbox then pixel crop",
        "existing_tests": "M.1",
        "known_limitations": "Too coarse for neighboring details; superseded by region render.",
        "independence": "INDEPENDENT_BUT_COARSE",
        "reuse": "NO_FOR_P2610A",
    },
    {
        "file": "Version10/src/PhaseT1_geometric_stirrup_evidence/beam_extent.py",
        "class_function": "find_beam_mark / compute_beam_scoped_extent",
        "purpose": "Production beam-scoped extent using R.1 by_beam cluster + nearest title",
        "rendering_method": "none (extent only)",
        "localization_method": "reinforcement association centroid + title nearest that point",
        "dependencies": "R.1 by_beam annotations",
        "supports_dxf_directly": True,
        "can_isolate_beam": True,
        "uses_beam_geometry": False,
        "uses_beam_title": True,
        "uses_annotation_association": True,
        "output_formats": [],
        "coordinate_system": "DXF mm",
        "existing_tests": "T1",
        "known_limitations": "NOT INDEPENDENT. find_beam_mark itself is reusable if near_xy is association-free.",
        "independence": "NOT_INDEPENDENT",
        "reuse": "find_beam_mark_pattern_only",
    },
    {
        "file": "Version10/src/PhaseT1_geometric_stirrup_evidence/geometry_envelope.py",
        "class_function": "build_geometry_envelope / _outline_bracket / compute_geometry_envelopes",
        "purpose": "Elevation envelope from outline/stirrup DIMENSION geometry once a mark XY is known",
        "rendering_method": "none (extent only)",
        "localization_method": "title mark + outline LINE clusters + stirrup DIMENSION bands",
        "dependencies": "compute_geometry_envelopes still resolves marks via annotations_by_beam; build_geometry_envelope does not",
        "supports_dxf_directly": True,
        "can_isolate_beam": True,
        "uses_beam_geometry": True,
        "uses_beam_title": True,
        "uses_annotation_association": "compute_geometry_envelopes YES; build_geometry_envelope NO",
        "output_formats": [],
        "coordinate_system": "DXF mm",
        "existing_tests": "T1.5",
        "known_limitations": "Do not call compute_geometry_envelopes with R.1 data. Reuse build_geometry_envelope with an independent mark.",
        "independence": "PARTIAL",
        "reuse": "YES_WITH_INDEPENDENT_MARK",
    },
    {
        "file": "Version10/src/PhaseT181_beam_render_validation / T182 / T183 RenderedBeams",
        "class_function": "ownership / adaptive / shared-ownership renderers",
        "purpose": "Production web-run beam PNGs",
        "rendering_method": "render_dxf_region_to_png with association/ownership extents",
        "localization_method": "owned annotations / BeamScopedAnnotations union",
        "dependencies": "T16/T18 ownership, R.1",
        "supports_dxf_directly": True,
        "can_isolate_beam": True,
        "uses_beam_geometry": True,
        "uses_beam_title": True,
        "uses_annotation_association": True,
        "output_formats": ["PNG"],
        "coordinate_system": "DXF extent → PNG",
        "existing_tests": "T181–T183 / QA30",
        "known_limitations": "NOT INDEPENDENT. Existing PNGs are diagnostic comparison only.",
        "independence": "NOT_INDEPENDENT",
        "reuse": "NO",
    },
    {
        "file": "Version10/src/PhaseP250_beam_evidence_crop_qa / P252–P2523",
        "class_function": "engineering_crop / evidence window",
        "purpose": "Vision evidence crops from owned bars/leaders/annotations",
        "rendering_method": "render_dxf_region_to_png",
        "localization_method": "owned bar/leader/annotation evidence window",
        "dependencies": "P2.5.x evidence packs",
        "supports_dxf_directly": True,
        "can_isolate_beam": True,
        "uses_beam_geometry": True,
        "uses_beam_title": True,
        "uses_annotation_association": True,
        "output_formats": ["PNG"],
        "coordinate_system": "DXF extent → PNG",
        "existing_tests": "P250 / P252.x",
        "known_limitations": "NOT INDEPENDENT of annotation/ownership association.",
        "independence": "NOT_INDEPENDENT",
        "reuse": "NO",
    },
    {
        "file": "Version10/src/PhaseQA2B0_pipeline_integration/pipeline_paths.py",
        "class_function": "CROP_PREFERENCE",
        "purpose": "Ordered lookup of existing production crop PNGs",
        "rendering_method": "none",
        "localization_method": "precomputed association-dependent renders",
        "dependencies": "web_run artefacts",
        "supports_dxf_directly": False,
        "can_isolate_beam": "PRECOMPUTED",
        "uses_beam_geometry": True,
        "uses_beam_title": True,
        "uses_annotation_association": True,
        "output_formats": ["PNG"],
        "coordinate_system": "n/a",
        "existing_tests": "QA2B0",
        "known_limitations": "Must not be the P2.6.10-A generation mechanism.",
        "independence": "NOT_INDEPENDENT",
        "reuse": "NO",
    },
]


__all__ = ["DISCOVERED_COMPONENTS"]
