"""
P2.6.10-D.3 — Hybrid Engineering Binding & Deterministic Calculation Compatibility.
MODEL_VERSION: 10.11.21

SHADOW ONLY. Bind D.2 hybrid semantics to existing deterministic engineering references.
No Claude. No DXF. No production. No cut-length / DL / steel calculation.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.21"
PHASE_ID = "P2.6.10-D.3"
PHASE_NAME = "Hybrid Engineering Binding & Deterministic Calculation Compatibility"
OUTPUT_DIRNAME = "PhaseP2610D3_hybrid_engineering_binding_compatibility"
GATE_VERSION = "P2610D3_HYBRID_ENGINEERING_BINDING_COMPATIBILITY_V1_0"

PRODUCTION_WRITE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"
ENGINEERING_CHANGES = "NONE"
LIVE_CLAUDE_CALL = False

P2610D2_OUTPUT_DIRNAME = "PhaseP2610D2_shadow_hybrid_semantic_resolver"
D2_POPULATION_NAME = "benchmark_population_manifest.json"
D2_HYBRID_NAME = "hybrid_beam_results.json"
P2610B1_OUTPUT_DIRNAME = "PhaseP2610B1_population_generalization"
POPULATION_MANIFEST_NAME = "population_manifest.json"

EXPECTED_POPULATION_SIZE = 16

STATUS_BOUND = "BOUND"
STATUS_PARTIAL = "PARTIALLY_BOUND"
STATUS_AMBIGUOUS = "AMBIGUOUS"
STATUS_MISSING_GEOM = "MISSING_GEOMETRY"
STATUS_MISSING_SUPPORT = "MISSING_SUPPORT_REFERENCE"
STATUS_MISSING_RULE = "MISSING_RULE_REFERENCE"
STATUS_UNSUPPORTED = "UNSUPPORTED"
STATUS_INVALID = "INVALID_INPUT"

BEAM_COMPATIBLE = "ENGINEERING_COMPATIBLE"
BEAM_PARTIAL = "ENGINEERING_PARTIALLY_COMPATIBLE"
BEAM_AMBIGUOUS = "ENGINEERING_AMBIGUOUS"
BEAM_INCOMPATIBLE = "ENGINEERING_INCOMPATIBLE"

SUPPORT_SCOPES_NEEDING_SUPPORT = (
    "LEFT_SUPPORT",
    "RIGHT_SUPPORT",
    "BOTH_SUPPORTS",
    "INTERMEDIATE_SUPPORT",
    "PARTIAL_LEFT",
    "PARTIAL_RIGHT",
    "PARTIAL_SUPPORT",
)

RULE_CUT_LENGTH = "DETERMINISTIC_LONGITUDINAL_CUT_LENGTH_RULE"
RULE_DL = "DETERMINISTIC_DEVELOPMENT_LENGTH_RULE"
RULE_ANCHORAGE = "DETERMINISTIC_ANCHORAGE_RULE"
RULE_HOOK = "DETERMINISTIC_HOOK_BEND_RULE"
RULE_STIRRUP_ENG = "DETERMINISTIC_STIRRUP_ENGINEERING_RULE"
RULE_SPACER = "DETERMINISTIC_SPACER_ENGINEERING_RULE"
