"""
Phase P2.5.2.3 — Target Beam Visual Completeness.
MODEL_VERSION: 10.6.8

Diagnostic / Vision-evidence rendering refinement ONLY.
No Claude. No engineering mutations. Candidate set frozen from P2.5.2.2.
"""
from __future__ import annotations

from typing import Tuple

MODEL_VERSION = "10.6.8"
PHASE_ID = "P2.5.2.3"
PHASE_NAME = "Target Beam Visual Completeness"
OUTPUT_DIRNAME = "PhaseP2523_target_beam_visual_completeness"
SCOPE = "FOURTH_SET_ONLY"
MODE = "TARGET_BEAM_VISUAL_COMPLETENESS_ONLY"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "NONE"

P2522_OUTPUT = "PhaseP2522_render_safe_annotation_bounds"
P2521_OUTPUT = "PhaseP2521_crop_readability_refinement"
P252_OUTPUT = "PhaseP252_vision_candidate_set"
P250_OUTPUT = "PhaseP250_beam_evidence_crop_qa"

PROVENANCE_P2522 = "P2522_RENDER_SAFE_EVIDENCE"
PROVENANCE_P2523 = "P2523_TARGET_BEAM_COMPLETE"

CROP_LOCAL_TARGET_COMPLETE = "local_target_complete"
CROP_BEAM_CONTEXT_TARGET_COMPLETE = "beam_context_target_complete"

# Pixel margins
TARGET_BEAM_EDGE_MARGIN_PX = 24
ANNOTATION_EDGE_MARGIN_PX = 24
EXPAND_BUFFER_PX = 8
BG_LUMA_THRESHOLD = 245

# Local critical beam half-span around annotation (mm) — aligned with P2.5.2.1 family
CRITICAL_BEAM_HALF_SPAN_MM = 1800.0
CRITICAL_BEAM_HALF_SPAN_CONTEXT_MM = 3200.0
GEOMETRY_PAD_MM = 60.0

# Expansion guardrails
MAX_RENDER_COMPLETENESS_ITERS = 4
MAX_SINGLE_SIDE_EXPANSION_MM = 750.0
MAX_TOTAL_EXPANSION_MM = 1500.0
MAX_REFINED_WIDTH_MM = 9000.0
MAX_REFINED_HEIGHT_MM = 7000.0
EXTREME_CROP_HEIGHT_MM = 10000.0
EXTREME_CROP_WIDTH_MM = 50000.0

# Status
COMPLETENESS_PASS = "PASS"
COMPLETENESS_PARTIAL = "PARTIAL"
COMPLETENESS_FAIL = "FAIL"
COMPLETENESS_REVIEW = "REVIEW"

# Reason codes
RC_TARGET_BEAM_VISIBLE = "TARGET_BEAM_VISIBLE"
RC_TARGET_BEAM_EDGE_CLIPPED = "TARGET_BEAM_EDGE_CLIPPED"
RC_TARGET_BEAM_EDGE_RISK = "TARGET_BEAM_EDGE_RISK"
RC_TARGET_BEAM_GEOMETRY_MISSING = "TARGET_BEAM_GEOMETRY_MISSING"
RC_TARGET_REINFORCEMENT_VISIBLE = "TARGET_REINFORCEMENT_VISIBLE"
RC_TARGET_REINFORCEMENT_CLIPPED = "TARGET_REINFORCEMENT_CLIPPED"
RC_TOP_REINFORCEMENT_CLIPPED = "TOP_REINFORCEMENT_CLIPPED"
RC_ANNOTATION_VISIBLE = "ANNOTATION_VISIBLE"
RC_LEADER_VISIBLE = "LEADER_VISIBLE"
RC_ANNOTATION_BEAM_RELATION_VISIBLE = "ANNOTATION_BEAM_RELATION_VISIBLE"
RC_INSUFFICIENT_BEAM_CONTEXT = "INSUFFICIENT_BEAM_CONTEXT"
RC_EXCESSIVE_CONTEXT = "EXCESSIVE_CONTEXT"
RC_CROP_EXPANDED = "CROP_EXPANDED"
RC_MAX_EXPANSION_REACHED = "MAX_EXPANSION_REACHED"
RC_REJECTED_PHYSICAL_BAR_EXCLUDED = "REJECTED_PHYSICAL_BAR_EXCLUDED"
RC_NO_SYNTHETIC_GEOMETRY = "NO_SYNTHETIC_GEOMETRY"

EXPECTED_VISION_CANDIDATES = 14
GOLDEN_OCR_SAMPLE = r"4L-Y12@\X100C/C"
KNOWN_PROBLEM_BEAMS = ("B82", "B143", "B144", "B175", "B178")

BBox = Tuple[float, float, float, float]
