"""Property resolver type constants — Phase G.5.3.2."""

from __future__ import annotations

from typing import FrozenSet

RESOLUTION_DIRECT = "DIRECT"
RESOLUTION_IDENTICAL = "IDENTICAL"
RESOLUTION_HIGHEST_CONFIDENCE = "HIGHEST_CONFIDENCE"
RESOLUTION_MAJORITY = "MAJORITY"
RESOLUTION_WEIGHTED_MAJORITY = "WEIGHTED_MAJORITY"
RESOLUTION_CONFLICT = "CONFLICT"
RESOLUTION_UNKNOWN = "UNKNOWN"

VALID_RESOLUTION_STRATEGIES: FrozenSet[str] = frozenset({
    RESOLUTION_DIRECT,
    RESOLUTION_IDENTICAL,
    RESOLUTION_HIGHEST_CONFIDENCE,
    RESOLUTION_MAJORITY,
    RESOLUTION_WEIGHTED_MAJORITY,
    RESOLUTION_CONFLICT,
    RESOLUTION_UNKNOWN,
})

RESOLUTION_STATUS_RESOLVED = "RESOLVED"
RESOLUTION_STATUS_CONFLICT = "CONFLICT"
RESOLUTION_STATUS_UNRESOLVED = "UNRESOLVED"

CREATED_PHASE = "G.5.3.2"
PREFIX_RESOLVED = "RES_PROP"
PREFIX_RESOLUTION_REGISTRY = "PROP_RESOLUTION_REGISTRY"
