"""Property parser type constants — Phase G.5.3.1."""

from __future__ import annotations

from typing import FrozenSet

PROP_DIAMETER = "DIAMETER"
PROP_QUANTITY = "QUANTITY"
PROP_SPACING = "SPACING"
PROP_BAR_TYPE = "BAR_TYPE"
PROP_REINFORCEMENT_CODE = "REINFORCEMENT_CODE"
PROP_BAR_MARK = "BAR_MARK"
PROP_HOOK = "HOOK"
PROP_HOOK_DIRECTION = "HOOK_DIRECTION"
PROP_SHAPE_CODE = "SHAPE_CODE"
PROP_CUT_LENGTH = "CUT_LENGTH"
PROP_BAR_LENGTH = "BAR_LENGTH"
PROP_START_OFFSET = "START_OFFSET"
PROP_END_OFFSET = "END_OFFSET"
PROP_LEVEL = "LEVEL"
PROP_ZONE = "ZONE"
PROP_CALLOUT = "CALLOUT"
PROP_NOTE = "NOTE"
PROP_LEADER = "LEADER"
PROP_BLOCK = "BLOCK"
PROP_TEXT = "TEXT"
PROP_UNKNOWN = "UNKNOWN"

VALID_PROPERTY_TYPES: FrozenSet[str] = frozenset({
    PROP_DIAMETER,
    PROP_QUANTITY,
    PROP_SPACING,
    PROP_BAR_TYPE,
    PROP_REINFORCEMENT_CODE,
    PROP_BAR_MARK,
    PROP_HOOK,
    PROP_HOOK_DIRECTION,
    PROP_SHAPE_CODE,
    PROP_CUT_LENGTH,
    PROP_BAR_LENGTH,
    PROP_START_OFFSET,
    PROP_END_OFFSET,
    PROP_LEVEL,
    PROP_ZONE,
    PROP_CALLOUT,
    PROP_NOTE,
    PROP_LEADER,
    PROP_BLOCK,
    PROP_TEXT,
    PROP_UNKNOWN,
})

PARSE_STATUS_PARSED = "PARSED"
PARSE_STATUS_UNPARSED = "UNPARSED"

VALID_PARSE_STATUSES: FrozenSet[str] = frozenset({
    PARSE_STATUS_PARSED,
    PARSE_STATUS_UNPARSED,
})

UNIT_MILLIMETRE = "mm"
UNIT_NONE = ""
UNIT_COUNT = "count"

PARSER_NAME_TEXT = "TEXT_REINFORCEMENT_PARSER"
PARSER_VERSION = "1.0.0"
CREATED_PHASE = "G.5.3.1"

TEXT_SOURCE_TYPES = frozenset({"TEXT", "NOTE", "CALLOUT", "DIMENSION"})
NON_TEXT_SOURCE_TYPES = frozenset({"SKETCH", "LEADER", "BLOCK", "UNKNOWN"})

REINFORCEMENT_PARSE_TYPES = frozenset({
    PROP_DIAMETER,
    PROP_QUANTITY,
    PROP_SPACING,
    PROP_BAR_TYPE,
    PROP_REINFORCEMENT_CODE,
})
