"""Calculation index type constants — Phase I.4.5."""

from __future__ import annotations

from typing import Dict, FrozenSet

PREFIX_CALCULATION_INDEX = "CALC_INDEX"
PREFIX_CALCULATION_INDEX_REGISTRY = "CALC_INDEX_REGISTRY"
NAMESPACE_CALCULATION_INDEX = "CALCULATION_INDEX"

CREATED_PHASE = "I.4.5"
PHASE_LABEL = "Phase I.4.5"

CATEGORY_DEVELOPMENT_LENGTH = "DEVELOPMENT_LENGTH"
CATEGORY_HOOK_LENGTH = "HOOK_LENGTH"
CATEGORY_LAP_LENGTH = "LAP_LENGTH"
CATEGORY_CUT_LENGTH = "CUT_LENGTH"
CATEGORY_ANCHORAGE_LENGTH = "ANCHORAGE_LENGTH"
CATEGORY_BEND_ALLOWANCE = "BEND_ALLOWANCE"
CATEGORY_SHAPE_CODE = "SHAPE_CODE"
CATEGORY_STEEL_WEIGHT = "STEEL_WEIGHT"
CATEGORY_QUANTITY = "QUANTITY"
CATEGORY_BBS = "BBS"
CATEGORY_OTHER = "OTHER"

SUPPORTED_INDEX_CATEGORIES: FrozenSet[str] = frozenset({
    CATEGORY_DEVELOPMENT_LENGTH,
    CATEGORY_HOOK_LENGTH,
    CATEGORY_LAP_LENGTH,
    CATEGORY_CUT_LENGTH,
    CATEGORY_ANCHORAGE_LENGTH,
    CATEGORY_BEND_ALLOWANCE,
    CATEGORY_SHAPE_CODE,
    CATEGORY_STEEL_WEIGHT,
    CATEGORY_QUANTITY,
    CATEGORY_BBS,
    CATEGORY_OTHER,
})

CALCULATION_TYPE_TO_INDEX_CATEGORY: Dict[str, str] = {
    "DEVELOPMENT_LENGTH": CATEGORY_DEVELOPMENT_LENGTH,
    "HOOK": CATEGORY_HOOK_LENGTH,
    "BEND": CATEGORY_BEND_ALLOWANCE,
    "LAP_LENGTH": CATEGORY_LAP_LENGTH,
    "CURTAILMENT": CATEGORY_OTHER,
    "CUT_LENGTH": CATEGORY_CUT_LENGTH,
    "BAR_SCHEDULE": CATEGORY_BBS,
    "STEEL_WEIGHT": CATEGORY_STEEL_WEIGHT,
    "BOQ": CATEGORY_QUANTITY,
}

FORBIDDEN_REFERENCE_VALUE_KEYS: FrozenSet[str] = frozenset({
    "result_value",
    "development_length_mm",
    "hook_length_mm",
    "cut_length_mm",
    "lap_length_mm",
    "weight_kg",
    "quantity",
})
