"""
Phase P2.6.2 — Selective Vision Candidate Gate.
MODEL_VERSION: 10.11.2

Shadow / research only. Deterministic production remains sole authority.
No engineering recompute. No production insert.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.2"
PHASE_ID = "P2.6.2"
PHASE_NAME = "Selective Vision Candidate Gate"
OUTPUT_DIRNAME = "PhaseP262_selective_vision_candidate_gate"
SCOPE = "FROZEN_P261_STRATIFIED_SAMPLE"
MODE = "GATE_SHADOW"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P262_SELECTIVE_GATE_V1_1"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

SAMPLE_SEED = 2611101
FROZEN_SAMPLE_BEAMS = 75
MAX_LIVE_CALLS = 40

MODE_REPLAY = "REPLAY_P261_CACHED"
MODE_LIVE = "LIVE_API"

P261_OUTPUT_DIRNAME = "PhaseP261_stratified_vision_candidate_recovery"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"
DECISION_HOLD = "HOLD"

PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"

CALL_REASONS = (
    "STIRRUP_TEXT_NO_OBJECT",
    "OCR_CORRUPTED_STIRRUP",
    "INCOMPLETE_PARSE",
    "UNASSOCIATED_REINFORCEMENT",
    "MISSING_DETERMINISTIC_OBJECT",
    "OTHER",
)
SKIP_REASONS = (
    "MATCHING_OBJECT_EXISTS",
    "COMPLETE_PARSE",
    "NO_PRODUCTION_GAP",
    "STRONG_DETERMINISTIC_COVERAGE",
)

DET_ALREADY = "ALREADY_DETECTED"

STRATA = ("DIFFICULT", "NORMAL", "EASY")
TYPE_GROUPS = (
    "STIRRUP",
    "LONGITUDINAL_REINFORCEMENT",
    "SIDE_FACE_REINFORCEMENT",
    "OTHER",
)
