"""
Phase P2.6.7 — Live Semantic Arbitration Benchmark & Repeatability Test.
MODEL_VERSION: 10.11.7

Isolated live shadow / research benchmark.
Does not change P2.6.4, P2.6.5, or P2.6.6 routing.
No engineering recompute. No production insert. No DUPLICATE->SKIP rule.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.7"
PHASE_ID = "P2.6.7"
PHASE_NAME = "Live Semantic Arbitration Benchmark & Repeatability Test"
OUTPUT_DIRNAME = "PhaseP267_live_semantic_arbitration"
SCOPE = "P266_TARGET_LIVE_SHADOW"
MODE = "SHADOW_RESEARCH"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P267_LIVE_SEMANTIC_ARBITRATION_V1_0"
P264_GATE_VERSION = "P264_SELECTIVE_ROLE_GAP_GATE_V1_0"
P265_GATE_VERSION = "P265_SPATIAL_CONTEXT_LONGITUDINAL_V1_0"
P266_GATE_VERSION = "P266_SEMANTIC_LONGITUDINAL_RESOLVER_V1_0"

CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

SAMPLE_SEED = 2611101
TARGET_BEAMS = 29
ROLE_COVERAGE_GAP_BEAMS = 18
FULLY_COVERED_DIAGNOSTIC_BEAMS = 11
PRIMARY_PASSES = 1
REPEAT_PASSES = 1
EXPECTED_LIVE_CALLS = TARGET_BEAMS * (PRIMARY_PASSES + REPEAT_PASSES)

MODE_LIVE = "LIVE_API"
MODE_REPARSE = "REPARSE_STORED_LIVE_RAW"
PASS_PRIMARY = "LIVE_PRIMARY"
PASS_REPEAT = "LIVE_REPEAT"

P266_OUTPUT_DIRNAME = "PhaseP266_semantic_longitudinal_resolver"
P265_OUTPUT_DIRNAME = "PhaseP265_spatial_context_longitudinal"
P264_OUTPUT_DIRNAME = "PhaseP264_selective_role_gap_gate"

PROMPT_VERSION = "P267_LIVE_SEMANTIC_ARBITRATION_PROMPT_V1"
SCHEMA_VERSION = "P267_LIVE_SEMANTIC_SCHEMA_V1"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"
DECISION_HOLD = "HOLD"

COVER_FULL = "FULLY_COVERED"
COVER_LAYER = "ROLE_COVERAGE_GAP"

SEM_DISTINCT = "DISTINCT_REINFORCEMENT"
SEM_DUPLICATE = "DUPLICATE_OR_REPEAT"
SEM_AMBIGUOUS = "AMBIGUOUS"
SEM_UNSUPPORTED = "UNSUPPORTED"

LAYER_TOP = "TOP"
LAYER_BOTTOM = "BOTTOM"
LAYER_SIDE = "SIDE"
LAYER_UNKNOWN = "UNKNOWN"

REP_REPRESENTED = "REPRESENTED"
REP_NOT_REPRESENTED = "NOT_REPRESENTED"
REP_UNCERTAIN = "UNCERTAIN"

ALLOWED_DECISIONS = (SEM_DISTINCT, SEM_DUPLICATE, SEM_AMBIGUOUS, SEM_UNSUPPORTED)
ALLOWED_LAYERS = (LAYER_TOP, LAYER_BOTTOM, LAYER_SIDE, LAYER_UNKNOWN)
ALLOWED_REPRESENTATION = (REP_REPRESENTED, REP_NOT_REPRESENTED, REP_UNCERTAIN)

ALLOWED_DECISIONS_FINAL = (
    "LIVE_SEMANTIC_VALIDATED",
    "LIVE_SEMANTIC_PARTIALLY_VALIDATED",
    "REFINE_SEMANTIC_ARBITRATION",
    "LIVE_BENCHMARK_FAILED",
)

CACHE_BYPASS = True
MAX_LIVE_CALLS = EXPECTED_LIVE_CALLS
