"""
Phase P2.5.2 — Vision Candidate Set + Visual Evidence Package.
MODEL_VERSION: 10.6.5

Deterministic only. No Claude. No engineering mutations.
"""
from __future__ import annotations

MODEL_VERSION = "10.6.5"
PHASE_ID = "P2.5.2"
PHASE_NAME = "Vision Candidate Set + Visual Evidence Package"
OUTPUT_DIRNAME = "PhaseP252_vision_candidate_set"
SCOPE = "FOURTH_SET_ONLY"
MODE = "CANDIDATE_EVIDENCE_PACKAGING_ONLY"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "NONE"

P251_OUTPUT = "PhaseP251_quantity_intent_schema"
P250_OUTPUT = "PhaseP250_beam_evidence_crop_qa"

# Priorities
P0 = "P0"
P1 = "P1"
P2 = "P2"
P3 = "P3"

# Selection outcomes
OUTCOME_CANDIDATE = "VISION_CANDIDATE"
OUTCOME_DEFERRED = "DEFERRED"
OUTCOME_EXCLUDED = "EXCLUDED"

# Reason codes
REASON_UNRESOLVED_QUANTITY = "UNRESOLVED_QUANTITY"
REASON_AMBIGUOUS_QUANTITY = "AMBIGUOUS_QUANTITY"
REASON_OCR_CORRUPTION = "OCR_CORRUPTION"
REASON_STIRRUP_PATTERN_UNPARSED = "STIRRUP_PATTERN_UNPARSED"
REASON_SEMANTIC_CONTEXT_REQUIRED = "SEMANTIC_CONTEXT_REQUIRED"
REASON_ROLE_CONTEXT_REQUIRED = "ROLE_CONTEXT_REQUIRED"
REASON_DIAMETER_CONTEXT_REQUIRED = "DIAMETER_CONTEXT_REQUIRED"
REASON_NON_QUANTITY_NOTE = "NON_QUANTITY_NOTE"
REASON_INSUFFICIENT_DETERMINISTIC_EVIDENCE = "INSUFFICIENT_DETERMINISTIC_EVIDENCE"
REASON_INSUFFICIENT_VISUAL_EVIDENCE = "INSUFFICIENT_VISUAL_EVIDENCE"
REASON_VISION_NOT_REQUIRED = "VISION_NOT_REQUIRED"
REASON_DEFER_ENGINEERING_RULE = "DEFER_ENGINEERING_RULE"

VISION_STATUS_PENDING = "PENDING"

# Extreme crop regression thresholds (mm) — aligned with P2.5.0.1
EXTREME_CROP_HEIGHT_MM = 10000.0
EXTREME_CROP_WIDTH_MM = 50000.0

# Known golden texts
GOLDEN_OCR_SAMPLE = r"4L-Y12@\X100C/C"
GOLDEN_DEV_NOTE = "Ld"
GOLDEN_SFR_NOTE = "S.F.R.ON EACH FACE"
