"""
P2.6.10-D.1 — Vision Semantic Contract & Hybrid Resolution Foundation.
MODEL_VERSION: 10.11.19

SHADOW ONLY. No Claude. No DXF. No production. No engineering mutation.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.19"
PHASE_ID = "P2.6.10-D.1"
PHASE_NAME = "Vision Semantic Contract & Hybrid Resolution Foundation"
OUTPUT_DIRNAME = "PhaseP2610D1_vision_semantic_contract_hybrid_foundation"
GATE_VERSION = "P2610D1_VISION_SEMANTIC_CONTRACT_HYBRID_RESOLUTION_FOUNDATION_V1_0"
CONTRACT_VERSION = "P2610D1_HYBRID_AUTHORITY_CONTRACT_V1"

PRODUCTION_WRITE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"
ENGINEERING_CHANGES = "NONE"
LIVE_CLAUDE_CALL = False

MODE_OFFLINE = "OFFLINE_VALIDATION"

# Single configurable threshold. Business logic must read this, not literals.
VISION_MIN_CONFIDENCE = 0.70

SUPPORTED_DIAMETERS = (8, 10, 12, 16, 20, 25, 32)
ALLOWED_LAYERS = ("TOP", "BOTTOM", "STIRRUP", "SIDE_FACE", "SIDE", "OTHER", "UNKNOWN")
ALLOWED_ROLES = ("MAIN", "EXTRA", "UNKNOWN")
ALLOWED_SCOPES = (
    "FULL_SPAN",
    "LEFT_SUPPORT",
    "RIGHT_SUPPORT",
    "BOTH_SUPPORTS",
    "MIDSPAN",
    "PARTIAL_LEFT",
    "PARTIAL_RIGHT",
    "PARTIAL_SUPPORT",
    "UNKNOWN",
)

P2610C3_OUTPUT_DIRNAME = "PhaseP2610C3_visual_completeness_claude_shadow"
P2610C5_OUTPUT_DIRNAME = "PhaseP2610C5_stratified_vision_semantic_benchmark"
P2610C1C2_OUTPUT_DIRNAME = "PhaseP2610C1C2_evidence_inventory_candidate_selection"
C3_SIX_BEAM_NAME = "six_beam_benchmark.json"
C5_SAMPLE_NAME = "selected_sample.json"
C5_MANIFEST_NAME = "benchmark_manifest.json"

AUTH_VISION = "VISION_PREFERRED"
AUTH_DET = "DETERMINISTIC"
AUTH_DET_ENG = "DETERMINISTIC_ENGINEERING"
AUTH_PRODUCTION = "DETERMINISTIC_PRODUCTION"

REASON_ACCEPTED = "VISION_ACCEPTED"
REASON_REJECTED = "VISION_REJECTED"
REASON_LOW_CONF = "VISION_LOW_CONFIDENCE"
REASON_SCHEMA = "VISION_SCHEMA_INVALID"
REASON_INCONSISTENT = "VISION_SEMANTIC_INCONSISTENT"
REASON_FALLBACK = "DETERMINISTIC_FALLBACK"
REASON_DET_AUTHORITY = "DETERMINISTIC_AUTHORITY"
REASON_VISION_ONLY = "VISION_ONLY_GROUP"
REASON_DET_ONLY = "DETERMINISTIC_ONLY_GROUP"
REASON_NO_VALUE = "NO_VALUE"
