"""
Phase P2.6.9 — Reinforcement Group Interpretation Benchmark.
MODEL_VERSION: 10.11.9

Shadow / research only. Does not change P2.6.4–P2.6.8 routing.
No engineering recompute. No production insert. No recovery.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.9"
PHASE_ID = "P2.6.9"
PHASE_NAME = "Reinforcement Group Interpretation Benchmark"
OUTPUT_DIRNAME = "PhaseP269_reinforcement_group_interpretation"
SCOPE = "GROUP_INTERPRETATION_SHADOW"
MODE = "SHADOW_RESEARCH"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P269_REINFORCEMENT_GROUP_INTERPRETATION_V1_0"
P268_GATE_VERSION = "P268_EVIDENCE_CONFLICT_ARBITRATION_V1_0"
P267_GATE_VERSION = "P267_LIVE_SEMANTIC_ARBITRATION_V1_0"
P266_GATE_VERSION = "P266_SEMANTIC_LONGITUDINAL_RESOLVER_V1_0"

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"

TARGET_BEAMS = 6
BENCHMARK_BEAMS = (
    ("Fourth", "B141"),
    ("Fourth", "B66"),
    ("Fourth", "B161"),
    ("Fifth", "B128"),
    ("Fifth", "B55"),
    ("Fifth", "B65"),
)

MODE_OFFLINE = "OFFLINE_BENCHMARK"

LAYER_TOP = "TOP"
LAYER_BOTTOM = "BOTTOM"
LAYER_SIDE = "SIDE"
LAYER_STIRRUP = "STIRRUP"
LAYER_SPACER = "SPACER"
LAYER_SUPPORT_TOP = "SUPPORT_TOP_ZONE"
LAYER_SUPPORT_BOTTOM = "SUPPORT_BOTTOM_ZONE"
LAYER_UNKNOWN = "UNKNOWN"

ROLE_MAIN = "MAIN"
ROLE_EXTRA = "EXTRA"
ROLE_SUPPORT = "SUPPORT"
ROLE_CURTAILMENT = "CURTAILMENT"
ROLE_CONTINUITY = "CONTINUITY"
ROLE_SIDE_FACE = "SIDE_FACE"
ROLE_STIRRUP = "STIRRUP"
ROLE_SPACER = "SPACER"
ROLE_OTHER = "OTHER"
ROLE_UNKNOWN = "UNKNOWN"

FAMILY_LONGITUDINAL = "LONGITUDINAL"
FAMILY_STIRRUP = "STIRRUP"
FAMILY_SIDE = "SIDE"
FAMILY_SPACER = "SPACER"
FAMILY_OTHER = "OTHER"

ZONE_FULL_SPAN = "FULL_SPAN"
ZONE_LEFT_SUPPORT = "LEFT_SUPPORT"
ZONE_RIGHT_SUPPORT = "RIGHT_SUPPORT"
ZONE_BOTH_SUPPORTS = "BOTH_SUPPORTS"
ZONE_MIDSPAN = "MIDSPAN"
ZONE_SUPPORT = "SUPPORT_ZONE"
ZONE_UNKNOWN = "UNKNOWN"

UNKNOWN = "UNKNOWN"

ERR_MERGED = "MERGED_DISTINCT_GROUPS"
ERR_SPLIT = "SPLIT_SINGLE_GROUP"
ERR_WRONG_LAYER = "WRONG_LAYER"
ERR_WRONG_ROLE = "WRONG_ROLE"
ERR_WRONG_SPEC = "WRONG_SPECIFICATION"
ERR_WRONG_COUNT = "WRONG_COUNT"
ERR_WRONG_ZONE = "WRONG_ZONE"
ERR_WRONG_EXTENT = "WRONG_EXTENT"
ERR_WRONG_ANN = "WRONG_ANNOTATION_ASSOCIATION"
ERR_MISSED = "MISSED_GROUP"
ERR_SPURIOUS = "SPURIOUS_GROUP"
ERR_UNKNOWN = "UNKNOWN_GROUP"
ERR_STIRRUP_MIX = "STIRRUP_LONGITUDINAL_MIXUP"

ASSOC_CORRECT = "correctly_grouped"
ASSOC_INCORRECT = "incorrectly_grouped"
ASSOC_UNGROUPED = "ungrouped"
ASSOC_DUPLICATED = "duplicated"
ASSOC_AMBIGUOUS = "ambiguous"

PRIMARY_FAMILIES = (FAMILY_LONGITUDINAL, FAMILY_STIRRUP)

ALLOWED_LAYERS = (
    LAYER_TOP,
    LAYER_BOTTOM,
    LAYER_SIDE,
    LAYER_STIRRUP,
    LAYER_SPACER,
    LAYER_SUPPORT_TOP,
    LAYER_SUPPORT_BOTTOM,
    LAYER_UNKNOWN,
)
ALLOWED_ROLES = (
    ROLE_MAIN,
    ROLE_EXTRA,
    ROLE_SUPPORT,
    ROLE_CURTAILMENT,
    ROLE_CONTINUITY,
    ROLE_SIDE_FACE,
    ROLE_STIRRUP,
    ROLE_SPACER,
    ROLE_OTHER,
    ROLE_UNKNOWN,
)
ALLOWED_FINAL = (
    "SAFE_SHADOW_BENCHMARK",
    "BENCHMARK_FAILED",
    "IMPLEMENTATION_FAILED",
)
ALLOWED_CAPABILITY = (
    "GROUP_INTERPRETATION_READY",
    "GROUP_INTERPRETATION_PARTIAL",
    "GROUP_INTERPRETATION_NOT_READY",
)

P266_OUTPUT_DIRNAME = "PhaseP266_semantic_longitudinal_resolver"
P267_OUTPUT_DIRNAME = "PhaseP267_live_semantic_arbitration"
P268_OUTPUT_DIRNAME = "PhaseP268_evidence_conflict_arbitration"

R13_BUCKETS = (
    ("top_main_bars", FAMILY_LONGITUDINAL, LAYER_TOP, ROLE_MAIN),
    ("top_extra_bars", FAMILY_LONGITUDINAL, LAYER_TOP, ROLE_EXTRA),
    ("bottom_main_bars", FAMILY_LONGITUDINAL, LAYER_BOTTOM, ROLE_MAIN),
    ("bottom_extra_bars", FAMILY_LONGITUDINAL, LAYER_BOTTOM, ROLE_EXTRA),
    ("stirrups", FAMILY_STIRRUP, LAYER_STIRRUP, ROLE_STIRRUP),
    ("side_face_reinforcement", FAMILY_SIDE, LAYER_SIDE, ROLE_SIDE_FACE),
    ("spacer_bars", FAMILY_SPACER, LAYER_SPACER, ROLE_SPACER),
)
