"""
Phase V.A.1.1 — workbook_recompute_validator.py
Validates the Estimation_Output.xlsx generated by V.B.1.
MODEL_VERSION: 6.6.3
"""
from __future__ import annotations

import pathlib
from typing import List

import openpyxl

from validation_recompute_models import (
    WorkbookRecomputeValidation,
    WorksheetRecomputeValidation,
)

_ROOT      = pathlib.Path(__file__).resolve().parents[3]
_WORKBOOK  = (
    _ROOT
    / "Version7/data/output/Production_Output/Estimation_Output.xlsx"
)

_EXPECTED_SHEETS = {
    "Bar Bending Schedule",
    "Beam Summary",
    "Steel Summary",
    "Diameter Summary",
    "Project Header",
    "General Notes",
}
_ENGINEERING_SHEET = "Bar Bending Schedule"
_HEADER_ROW        = 8   # row index (1-based) where BBS headers appear


class WorkbookRecomputeValidator:
    """
    Validates workbook existence, readability, structure, headers,
    engineering rows, totals, and steel summary.
    """

    def __init__(self, workbook_path: pathlib.Path = _WORKBOOK) -> None:
        self._path = workbook_path

    def validate(self) -> WorkbookRecomputeValidation:
        issues: List[str] = []

        if not self._path.exists():
            return WorkbookRecomputeValidation(
                workbook_path=str(self._path),
                exists=False,
                readable=False,
                corrupted=True,
                size_bytes=0,
                size_kb=0.0,
                sheet_names=[],
                total_sheets=0,
                total_rows=0,
                total_columns=0,
                has_data=False,
                validation_passed=False,
                issues=["Workbook file does not exist"],
            )

        size_bytes = self._path.stat().st_size
        size_kb    = round(size_bytes / 1024, 1)

        try:
            wb = openpyxl.load_workbook(str(self._path), data_only=True, read_only=True)
        except Exception as exc:
            return WorkbookRecomputeValidation(
                workbook_path=str(self._path),
                exists=True,
                readable=False,
                corrupted=True,
                size_bytes=size_bytes,
                size_kb=size_kb,
                sheet_names=[],
                total_sheets=0,
                total_rows=0,
                total_columns=0,
                has_data=False,
                validation_passed=False,
                issues=[f"Workbook not readable: {exc}"],
            )

        sheet_names  = wb.sheetnames
        ws_validations: List[WorksheetRecomputeValidation] = []
        total_rows   = 0
        total_cols   = 0

        for name in sheet_names:
            ws  = wb[name]
            rows = list(ws.iter_rows(values_only=True))
            nr   = len(rows)
            nc   = max((len(r) for r in rows), default=0)
            total_rows  += nr
            total_cols   = max(total_cols, nc)

            ws_issues: List[str] = []
            has_headers   = nr >= _HEADER_ROW
            has_data_rows = nr > _HEADER_ROW
            has_totals    = any(
                any(
                    isinstance(c, str) and "total" in c.lower()
                    for c in r
                    if c is not None
                )
                for r in rows
            )
            has_steel_summary = any(
                any(
                    isinstance(c, str) and ("steel" in c.lower() or "kg" in c.lower())
                    for c in r
                    if c is not None
                )
                for r in rows
            )

            if not has_headers:
                ws_issues.append(f"Sheet '{name}': no header row found")
            if not has_data_rows and name == _ENGINEERING_SHEET:
                ws_issues.append(f"Sheet '{name}': no data rows")

            ws_validations.append(
                WorksheetRecomputeValidation(
                    sheet_name=name,
                    row_count=nr,
                    col_count=nc,
                    has_headers=has_headers,
                    has_data_rows=has_data_rows,
                    has_totals_row=has_totals,
                    has_steel_summary=has_steel_summary,
                    validation_passed=len(ws_issues) == 0,
                    issues=ws_issues,
                )
            )
            issues.extend(ws_issues)

        missing_sheets = _EXPECTED_SHEETS - set(sheet_names)
        for ms in missing_sheets:
            issues.append(f"Expected sheet missing: '{ms}'")

        wb.close()

        has_data    = total_rows > 0
        passed      = len(issues) == 0

        return WorkbookRecomputeValidation(
            workbook_path=str(self._path),
            exists=True,
            readable=True,
            corrupted=False,
            size_bytes=size_bytes,
            size_kb=size_kb,
            sheet_names=sheet_names,
            total_sheets=len(sheet_names),
            total_rows=total_rows,
            total_columns=total_cols,
            has_data=has_data,
            validation_passed=passed,
            worksheet_validations=ws_validations,
            issues=issues,
        )
