"""Engineering Object type constants — Phase G.5.1 graph instantiation."""

from __future__ import annotations

from typing import FrozenSet

OBJECT_BEAM_IDENTIFIER = "BEAM_IDENTIFIER"
OBJECT_TOP_REINFORCEMENT = "TOP_REINFORCEMENT"
OBJECT_BOTTOM_REINFORCEMENT = "BOTTOM_REINFORCEMENT"
OBJECT_STIRRUP = "STIRRUP"
OBJECT_SIDE_FACE_REINFORCEMENT = "SIDE_FACE_REINFORCEMENT"
OBJECT_LEADER = "LEADER"
OBJECT_DIMENSION = "DIMENSION"
OBJECT_GENERAL_NOTE = "GENERAL_NOTE"
OBJECT_SECTION_MARKER = "SECTION_MARKER"
OBJECT_TEXT_NOTE = "TEXT_NOTE"
OBJECT_UNKNOWN = "UNKNOWN_OBJECT"

VALID_OBJECT_TYPES: FrozenSet[str] = frozenset({
    OBJECT_BEAM_IDENTIFIER,
    OBJECT_TOP_REINFORCEMENT,
    OBJECT_BOTTOM_REINFORCEMENT,
    OBJECT_STIRRUP,
    OBJECT_SIDE_FACE_REINFORCEMENT,
    OBJECT_LEADER,
    OBJECT_DIMENSION,
    OBJECT_GENERAL_NOTE,
    OBJECT_SECTION_MARKER,
    OBJECT_TEXT_NOTE,
    OBJECT_UNKNOWN,
})

CLASSIFICATION_SOURCE_SEMANTIC_ROLE = "SEMANTIC_ROLE"
CLASSIFICATION_SOURCE_SEMANTIC_GRAPH = "SEMANTIC_GRAPH"
CLASSIFICATION_SOURCE_RELATIONSHIP = "RELATIONSHIP"

ENGINEERING_STATUS_OBJECT_CREATED = "OBJECT_CREATED"
ENGINEERING_STATUS_OBJECT_VALIDATED = "OBJECT_VALIDATED"
ENGINEERING_STATUS_UNKNOWN_OBJECT = "UNKNOWN_OBJECT"

VALID_ENGINEERING_STATUSES: FrozenSet[str] = frozenset({
    ENGINEERING_STATUS_OBJECT_CREATED,
    ENGINEERING_STATUS_OBJECT_VALIDATED,
    ENGINEERING_STATUS_UNKNOWN_OBJECT,
})

LIFECYCLE_DISCOVERED = "DISCOVERED"
LIFECYCLE_CLASSIFIED = "CLASSIFIED"
LIFECYCLE_OBJECT_CREATED = "OBJECT_CREATED"
LIFECYCLE_VALIDATED = "VALIDATED"
LIFECYCLE_READY_FOR_PROPERTY_PARSING = "READY_FOR_PROPERTY_PARSING"

VALID_OBJECT_LIFECYCLE: FrozenSet[str] = frozenset({
    LIFECYCLE_DISCOVERED,
    LIFECYCLE_CLASSIFIED,
    LIFECYCLE_OBJECT_CREATED,
    LIFECYCLE_VALIDATED,
    LIFECYCLE_READY_FOR_PROPERTY_PARSING,
})

CREATED_PHASE = "G.5.1"
