"""
P2.6.10-D.2 — Shadow Hybrid Semantic Resolver.
MODEL_VERSION: 10.11.20

SHADOW ONLY. Applies the D.1 authority contract. No Claude. No DXF. No production.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.20"
PHASE_ID = "P2.6.10-D.2"
PHASE_NAME = "Shadow Hybrid Semantic Resolver"
OUTPUT_DIRNAME = "PhaseP2610D2_shadow_hybrid_semantic_resolver"
GATE_VERSION = "P2610D2_SHADOW_HYBRID_SEMANTIC_RESOLUTION_V1_0"

PRODUCTION_WRITE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"
ENGINEERING_CHANGES = "NONE"
LIVE_CLAUDE_CALL = False

P2610D1_OUTPUT_DIRNAME = "PhaseP2610D1_vision_semantic_contract_hybrid_foundation"
D1_POPULATION_NAME = "benchmark_population_manifest.json"
D1_CONTRACT_NAME = "hybrid_authority_contract.json"
D1_RESULTS_NAME = "P2.6.10-D.1_RESULTS.json"

# Fail-closed expected size from D.1. Not a beam-ID table.
EXPECTED_POPULATION_SIZE = 16

SRC_VISION = "VISION"
SRC_DET = "DETERMINISTIC"
SRC_UNRESOLVED = "UNRESOLVED"

REASON_VISION_VALID = "VISION_PREFERRED_VALID"
REASON_FALLBACK = "DETERMINISTIC_FALLBACK"
REASON_DET_AUTH = "DETERMINISTIC_AUTHORITY"
REASON_VISION_ONLY = "VISION_ONLY_GROUP"
REASON_DET_ONLY = "DETERMINISTIC_ONLY_GROUP"
REASON_AMBIGUOUS = "AMBIGUOUS_GROUP_MATCH"
REASON_UNRESOLVED = "UNRESOLVED"
REASON_POSSIBLE_DUP = "POSSIBLE_DUPLICATE"

CONFLICT_FIELDS = (
    "LAYER",
    "ROLE",
    "BAR_COUNT",
    "DIAMETER",
    "SPECIFICATION",
    "SUPPORT_SCOPE",
    "STIRRUP_IDENTIFICATION",
    "TARGET_IDENTITY",
)
