"""
Phase P2.6.5 — Spatial / Context-Aware Longitudinal Ambiguity Resolution.
MODEL_VERSION: 10.11.5

Shadow / research only. Does not change P2.6.4 production routing.
No engineering recompute. No production insert.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.5"
PHASE_ID = "P2.6.5"
PHASE_NAME = "Spatial / Context-Aware Longitudinal Ambiguity Resolution"
OUTPUT_DIRNAME = "PhaseP265_spatial_context_longitudinal"
SCOPE = "FROZEN_P261_STRATIFIED_SAMPLE"
MODE = "SHADOW_RESEARCH"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P265_SPATIAL_CONTEXT_LONGITUDINAL_V1_0"
P264_GATE_VERSION = "P264_SELECTIVE_ROLE_GAP_GATE_V1_0"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

SAMPLE_SEED = 2611101
FROZEN_SAMPLE_BEAMS = 75
MAX_LIVE_CALLS = 0

MODE_REPLAY = "REPLAY_P261_CACHED"
MODE_LIVE = "LIVE_API"

P261_OUTPUT_DIRNAME = "PhaseP261_stratified_vision_candidate_recovery"
P262_OUTPUT_DIRNAME = "PhaseP262_selective_vision_candidate_gate"
P263_OUTPUT_DIRNAME = "PhaseP263_longitudinal_aware_gate"
P264_OUTPUT_DIRNAME = "PhaseP264_selective_role_gap_gate"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"
DECISION_HOLD = "HOLD"

COVER_FULL = "FULLY_COVERED"
COVER_LAYER = "ROLE_COVERAGE_GAP"

COORDINATE_SPACE = "DXF_MODEL_MM"

# Categorical classifier thresholds, relative to envelope depth_mm.
# Documented and used for sensitivity analysis. Not GT-tuned per beam.
CLEARANCE_RATIO = 0.15
REPEAT_SEPARATION_RATIO = 0.50
SAME_LOCATION_RATIO = 0.15
CLUSTER_GAP_RATIO = 0.25
LEADER_TAIL_ASSOCIATION_MM = 500.0

STATUS_SKIP = "CONTEXT_SUPPORTS_SKIP"
STATUS_CALL = "CONTEXT_SUPPORTS_CALL"
STATUS_AMBIGUOUS = "CONTEXT_AMBIGUOUS"
STATUS_INSUFFICIENT = "CONTEXT_INSUFFICIENT"

EVIDENCE_CODES = (
    "SPATIAL_MATCH_STRONG",
    "SPATIAL_SEPARATION_STRONG",
    "TOP_PROXIMITY",
    "BOTTOM_PROXIMITY",
    "CROSS_LAYER_SEPARATION",
    "SAME_CLUSTER",
    "SEPARATE_CLUSTER",
    "REPEATED_SAME_LOCATION",
    "REPEATED_SEPARATE_LOCATION",
    "LEADER_SEPARATION",
    "ANNOTATION_CLUSTER_SEPARATION",
    "ZONE_BOUNDARY",
    "NO_RELIABLE_SPATIAL_EVIDENCE",
    "NO_PHYSICAL_BAR_GEOMETRY",
    "NO_ANNOTATION_XY",
    "NO_LEADER_GEOMETRY",
)

STIRRUP_CALL_REASONS = (
    "STIRRUP_TEXT_NO_OBJECT",
    "OCR_CORRUPTED_STIRRUP",
    "INCOMPLETE_PARSE",
)

P264_BASELINE = {
    "CALL_BEAMS": 37,
    "SKIP_BEAMS": 38,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.506667,
    "GATED_VISION_CANDIDATES": 101,
    "DUPLICATE_RATE_GATED": 0.465347,
    "GATED_PRECISION": 0.683168,
    "GATED_UNSUPPORTED_RATE": 0.108911,
    "GATED_AMBIGUOUS_RATE": 0.108911,
    "GATED_TRUE_RECOVERIES": 25,
    "RECOVERY_RETENTION_RATE": 0.961538,
    "FALSE_SKIPS": 1,
    "FALSE_CALLS": 13,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 67.5676,
    "STIRRUP_RETAINED": 18,
    "LONGITUDINAL_RETAINED": 7,
}

P263_BASELINE = {
    "CALL_BEAMS": 40,
    "SKIP_BEAMS": 35,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.466667,
    "GATED_VISION_CANDIDATES": 108,
    "DUPLICATE_RATE_GATED": 0.50,
    "GATED_PRECISION": 0.685185,
    "GATED_UNSUPPORTED_RATE": 0.101852,
    "GATED_TRUE_RECOVERIES": 25,
    "RECOVERY_RETENTION_RATE": 0.961538,
    "FALSE_SKIPS": 1,
    "FALSE_CALLS": 16,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 62.5,
}

P262_BASELINE = {
    "CALL_BEAMS": 38,
    "SKIP_BEAMS": 37,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.493333,
    "GATED_VISION_CANDIDATES": 118,
    "DUPLICATE_RATE_GATED": 0.533898,
    "GATED_PRECISION": 0.711864,
    "GATED_UNSUPPORTED_RATE": 0.09322,
    "GATED_TRUE_RECOVERIES": 22,
    "RECOVERY_RETENTION_RATE": 0.846154,
    "FALSE_SKIPS": 4,
    "FALSE_CALLS": 17,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 57.8947,
}

P261_BASELINE = {
    "CALL_BEAMS": 75,
    "SKIP_BEAMS": 0,
    "HOLD_BEAMS": 0,
    "CALL_REDUCTION": 0.0,
    "GATED_VISION_CANDIDATES": 207,
    "DUPLICATE_RATE_GATED": 0.657005,
    "GATED_PRECISION": 0.73913,
    "GATED_UNSUPPORTED_RATE": 0.062802,
    "GATED_TRUE_RECOVERIES": 26,
    "TRUE_RECOVERIES_PER_100_VISION_CALLS_GATED": 34.6667,
}
