"""Reinforcement calculation type constants — Phase I.2."""

from __future__ import annotations

from typing import Dict, FrozenSet

PREFIX_REBAR = "REBAR"
PREFIX_REBAR_GROUP = "REBAR_GROUP"
PREFIX_REBAR_REGISTRY = "REBAR_REGISTRY"
NAMESPACE_REBAR = "REBAR"

CREATED_PHASE = "I.2"
READINESS_PHASE = "I.2.1"
MODEL_VERSION = "I.2"

ROLE_TOP_MAIN = "TOP_MAIN"
ROLE_BOTTOM_MAIN = "BOTTOM_MAIN"
ROLE_EXTRA_TOP = "EXTRA_TOP"
ROLE_EXTRA_BOTTOM = "EXTRA_BOTTOM"
ROLE_SIDE_BAR = "SIDE_BAR"
ROLE_STIRRUP = "STIRRUP"
ROLE_LINK_BAR = "LINK_BAR"
ROLE_SPACER = "SPACER"
ROLE_STARTER = "STARTER"
ROLE_UNKNOWN = "UNKNOWN"

VALID_ENGINEERING_ROLES: FrozenSet[str] = frozenset({
    ROLE_TOP_MAIN,
    ROLE_BOTTOM_MAIN,
    ROLE_EXTRA_TOP,
    ROLE_EXTRA_BOTTOM,
    ROLE_SIDE_BAR,
    ROLE_STIRRUP,
    ROLE_LINK_BAR,
    ROLE_SPACER,
    ROLE_STARTER,
    ROLE_UNKNOWN,
})

BAR_TYPE_MAIN = "MAIN_BAR"
BAR_TYPE_EXTRA = "EXTRA_BAR"
BAR_TYPE_SIDE = "SIDE_BAR"
BAR_TYPE_STIRRUP = "STIRRUP"
BAR_TYPE_LINK = "LINK"
BAR_TYPE_SPACER = "SPACER"

VALID_BAR_TYPES: FrozenSet[str] = frozenset({
    BAR_TYPE_MAIN,
    BAR_TYPE_EXTRA,
    BAR_TYPE_SIDE,
    BAR_TYPE_STIRRUP,
    BAR_TYPE_LINK,
    BAR_TYPE_SPACER,
})

STATUS_NORMALIZED = "NORMALIZED"
STATUS_PARTIAL = "PARTIAL"
STATUS_INCOMPLETE = "INCOMPLETE"

VALID_BAR_STATUSES: FrozenSet[str] = frozenset({
    STATUS_NORMALIZED,
    STATUS_PARTIAL,
    STATUS_INCOMPLETE,
})

SPECIFICATION_TYPE_TO_ROLE: Dict[str, str] = {
    "TOP_MAIN_REINFORCEMENT": ROLE_TOP_MAIN,
    "BOTTOM_MAIN_REINFORCEMENT": ROLE_BOTTOM_MAIN,
    "EXTRA_TOP_REINFORCEMENT": ROLE_EXTRA_TOP,
    "EXTRA_BOTTOM_REINFORCEMENT": ROLE_EXTRA_BOTTOM,
    "STIRRUP": ROLE_STIRRUP,
    "LINK": ROLE_LINK_BAR,
    "EDGE_BAR": ROLE_SIDE_BAR,
    "HAUNCH_BAR": ROLE_EXTRA_TOP,
    "STARTER_BAR": ROLE_STARTER,
    "UNKNOWN": ROLE_UNKNOWN,
}

ROLE_TO_BAR_TYPE: Dict[str, str] = {
    ROLE_TOP_MAIN: BAR_TYPE_MAIN,
    ROLE_BOTTOM_MAIN: BAR_TYPE_MAIN,
    ROLE_EXTRA_TOP: BAR_TYPE_EXTRA,
    ROLE_EXTRA_BOTTOM: BAR_TYPE_EXTRA,
    ROLE_SIDE_BAR: BAR_TYPE_SIDE,
    ROLE_STIRRUP: BAR_TYPE_STIRRUP,
    ROLE_LINK_BAR: BAR_TYPE_LINK,
    ROLE_SPACER: BAR_TYPE_SPACER,
    ROLE_STARTER: BAR_TYPE_MAIN,
    ROLE_UNKNOWN: BAR_TYPE_MAIN,
}

ROLE_TO_POSITION: Dict[str, str] = {
    ROLE_TOP_MAIN: "TOP",
    ROLE_BOTTOM_MAIN: "BOTTOM",
    ROLE_EXTRA_TOP: "TOP",
    ROLE_EXTRA_BOTTOM: "BOTTOM",
    ROLE_SIDE_BAR: "SIDE",
    ROLE_STIRRUP: "TRANSVERSE",
    ROLE_LINK_BAR: "TRANSVERSE",
    ROLE_SPACER: "TRANSVERSE",
    ROLE_STARTER: "START",
    ROLE_UNKNOWN: "UNKNOWN",
}

REGISTRY_SCHEMA_KEYS: FrozenSet[str] = frozenset({
    "namespace",
    "phase",
    "registry_id",
    "bar_count",
    "group_count",
    "bar_ids",
    "group_ids",
    "specification_count",
    "processed_context_ids",
})
