"""
Phase P2.6.8 — Evidence-Conflict Arbitration / Layer-Aware Semantic Resolver.
MODEL_VERSION: 10.11.8

Shadow / research only. Does not change P2.6.4–P2.6.7 routing.
No engineering recompute. No production insert. No DUPLICATE->SKIP. No DISTINCT->CALL.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.8"
PHASE_ID = "P2.6.8"
PHASE_NAME = "Evidence-Conflict Arbitration / Layer-Aware Semantic Resolver"
OUTPUT_DIRNAME = "PhaseP268_evidence_conflict_arbitration"
SCOPE = "EVIDENCE_CONFLICT_SHADOW"
MODE = "SHADOW_RESEARCH"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P268_EVIDENCE_CONFLICT_ARBITRATION_V1_0"
P264_GATE_VERSION = "P264_SELECTIVE_ROLE_GAP_GATE_V1_0"
P265_GATE_VERSION = "P265_SPATIAL_CONTEXT_LONGITUDINAL_V1_0"
P266_GATE_VERSION = "P266_SEMANTIC_LONGITUDINAL_RESOLVER_V1_0"
P267_GATE_VERSION = "P267_LIVE_SEMANTIC_ARBITRATION_V1_0"

CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"

SAMPLE_SEED = 2611101
TARGET_BEAMS = 29

MODE_OFFLINE = "OFFLINE_ARBITRATION"
MODE_LIVE = "LIVE_CLASSIFY"

P266_OUTPUT_DIRNAME = "PhaseP266_semantic_longitudinal_resolver"
P267_OUTPUT_DIRNAME = "PhaseP267_live_semantic_arbitration"
P265_OUTPUT_DIRNAME = "PhaseP265_spatial_context_longitudinal"
P264_OUTPUT_DIRNAME = "PhaseP264_selective_role_gap_gate"

PROMPT_VERSION = "P268_EVIDENCE_CONFLICT_PROMPT_V1"
SCHEMA_VERSION = "P268_EVIDENCE_CONFLICT_SCHEMA_V1"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"

COVER_FULL = "FULLY_COVERED"
COVER_LAYER = "ROLE_COVERAGE_GAP"

SEM_DISTINCT = "DISTINCT_REINFORCEMENT"
SEM_DUPLICATE = "DUPLICATE_OR_REPEAT"
SEM_AMBIGUOUS = "AMBIGUOUS"
SEM_UNSUPPORTED = "UNSUPPORTED"
SEM_UNUSABLE = "SEMANTIC_UNUSABLE"

LAYER_TOP = "TOP"
LAYER_BOTTOM = "BOTTOM"
LAYER_SIDE = "SIDE"
LAYER_STIRRUP = "STIRRUP"
LAYER_SPACER = "SPACER"
LAYER_SUPPORT_TOP = "SUPPORT_TOP_ZONE"
LAYER_SUPPORT_BOTTOM = "SUPPORT_BOTTOM_ZONE"
LAYER_UNKNOWN = "UNKNOWN"

DET_ALREADY = "ALREADY_DETECTED"
DET_MISSING = "POTENTIALLY_MISSING"
DET_CONFLICT = "CONFLICTING"

PHYS_DISTINCT = "DETERMINISTIC_DISTINCT"
PHYS_DUPLICATE = "DETERMINISTIC_DUPLICATE"
PHYS_AMBIGUOUS = "DETERMINISTIC_AMBIGUOUS"
PHYS_INSUFFICIENT = "DETERMINISTIC_INSUFFICIENT"

CONFLICT_NONE = "NO_CONFLICT"
CONFLICT_EQUAL_SPEC_LAYER = "EQUAL_SPEC_DIFFERENT_LAYER"
CONFLICT_EQUAL_SPEC_TARGET = "EQUAL_SPEC_DIFFERENT_TARGET"
CONFLICT_SEM_DUP_PHYS_DIST = "SEMANTIC_DUPLICATE_PHYSICAL_DISTINCT"
CONFLICT_SEM_DIST_PHYS_DUP = "SEMANTIC_DISTINCT_PHYSICAL_DUPLICATE"
CONFLICT_ROLE = "ROLE_CONFLICT"
CONFLICT_LEADER = "LEADER_CONFLICT"
CONFLICT_SPATIAL = "SPATIAL_CONFLICT"
CONFLICT_LAYER = "LAYER_CONFLICT"
CONFLICT_SPEC = "SPECIFICATION_CONFLICT"
CONFLICT_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"

ARB_AGREE = "AGREE"
ARB_SEM_SUPPORTS = "SEMANTIC_SUPPORTS_DETERMINISTIC"
ARB_DET_OVERRIDES = "DETERMINISTIC_OVERRIDES_SEMANTIC"
ARB_REVIEW = "CONFLICT_REQUIRES_REVIEW"
ARB_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"
ARB_UNUSABLE = "SEMANTIC_UNUSABLE"

STRENGTH_STRONG = "STRONG"
STRENGTH_MEDIUM = "MEDIUM"
STRENGTH_WEAK = "WEAK"
STRENGTH_NONE = "NONE"

SRC_DET_PHYSICAL = "deterministic_physical"
SRC_DET_LAYER = "deterministic_role_layer"
SRC_LEADER = "leader_association"
SRC_SPATIAL = "spatial_topological"
SRC_DRAWING = "normalized_drawing_semantics"
SRC_LLM = "llm_semantic"

ALLOWED_SEMANTIC = (SEM_DISTINCT, SEM_DUPLICATE, SEM_AMBIGUOUS, SEM_UNSUPPORTED, SEM_UNUSABLE)
ALLOWED_LAYERS = (
    LAYER_TOP,
    LAYER_BOTTOM,
    LAYER_SIDE,
    LAYER_STIRRUP,
    LAYER_SPACER,
    LAYER_SUPPORT_TOP,
    LAYER_SUPPORT_BOTTOM,
    LAYER_UNKNOWN,
)
ALLOWED_CONFLICTS = (
    CONFLICT_NONE,
    CONFLICT_EQUAL_SPEC_LAYER,
    CONFLICT_EQUAL_SPEC_TARGET,
    CONFLICT_SEM_DUP_PHYS_DIST,
    CONFLICT_SEM_DIST_PHYS_DUP,
    CONFLICT_ROLE,
    CONFLICT_LEADER,
    CONFLICT_SPATIAL,
    CONFLICT_LAYER,
    CONFLICT_SPEC,
    CONFLICT_INSUFFICIENT,
)
ALLOWED_ARBITRATION = (
    ARB_AGREE,
    ARB_SEM_SUPPORTS,
    ARB_DET_OVERRIDES,
    ARB_REVIEW,
    ARB_INSUFFICIENT,
    ARB_UNUSABLE,
)
ALLOWED_FINAL = (
    "SAFE_SHADOW_DIAGNOSTIC",
    "UNSAFE_SHADOW_DIAGNOSTIC",
    "BENCHMARK_FAILED",
    "IMPLEMENTATION_FAILED",
)

REASON_CODES = (
    "LAYER_MATCH",
    "LAYER_MISMATCH",
    "PHYSICAL_TARGET_MATCH",
    "PHYSICAL_TARGET_MISMATCH",
    "SPEC_MATCH",
    "SPEC_MISMATCH",
    "LEADER_MATCH",
    "LEADER_MISMATCH",
    "SPATIAL_MATCH",
    "SPATIAL_MISMATCH",
    "SEMANTIC_DUPLICATE",
    "SEMANTIC_DISTINCT",
    "DETERMINISTIC_DISTINCT",
    "DETERMINISTIC_DUPLICATE",
    "DETERMINISTIC_EVIDENCE_STRONGER",
    "SEMANTIC_EVIDENCE_WEAKER",
    "INSUFFICIENT_PHYSICAL_EVIDENCE",
    "SEMANTIC_UNUSABLE",
    "EQUAL_SPEC_CROSS_LAYER",
    "ANNOTATION_REPRESENTATION_ONLY",
)
