"""
Phase P2.5.3 — Claude Vision Interpretation Pilot.
MODEL_VERSION: 10.7.0

PILOT ONLY — Claude is an interpreter, not an engineering authority.
No production promotion. No steel/BBS/Excel mutation.
"""
from __future__ import annotations

MODEL_VERSION = "10.7.0"
PHASE_ID = "P2.5.3"
PHASE_NAME = "Claude Vision Interpretation Pilot"
OUTPUT_DIRNAME = "PhaseP253_claude_vision_interpretation_pilot"
SCOPE = "FOURTH_SET_ONLY"
MODE = "PILOT_ONLY_NO_PRODUCTION_PROMOTION"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "PILOT_ISOLATED"

P2523_OUTPUT = "PhaseP2523_target_beam_visual_completeness"
P252_OUTPUT = "PhaseP252_vision_candidate_set"
P251_OUTPUT = "PhaseP251_quantity_intent_schema"

PROMPT_VERSION = "P253_VISION_PROMPT_V1"
SCHEMA_VERSION = "P253_INTERPRETATION_SCHEMA_V1"

EVIDENCE_MODE_LOCAL_ONLY = "LOCAL_ONLY"
EVIDENCE_MODE_LOCAL_PLUS_CONTEXT = "LOCAL_PLUS_CONTEXT"
PRIMARY_EVIDENCE_MODE = EVIDENCE_MODE_LOCAL_PLUS_CONTEXT

EXPECTED_VISION_CANDIDATES = 14

# Interpretation statuses
STATUS_RESOLVED = "RESOLVED"
STATUS_PARTIAL = "PARTIAL"
STATUS_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"
STATUS_CONFLICT = "CONFLICT"

REINFORCEMENT_TYPES = (
    "LONGITUDINAL_BAR",
    "STIRRUP",
    "SIDE_FACE",
    "DEVELOPMENT_NOTE",
    "OTHER",
    "UNKNOWN",
)

# Evaluation outcomes
EVAL_EXACT = "EXACT"
EVAL_PARTIAL = "PARTIAL"
EVAL_INCORRECT = "INCORRECT"
EVAL_HALLUCINATION = "HALLUCINATION"
EVAL_APPROPRIATE_ABSTENTION = "APPROPRIATE_ABSTENTION"
EVAL_CONFLICT_DETECTED = "CONFLICT_DETECTED"
EVAL_GT_UNAVAILABLE = "GROUND_TRUTH_UNAVAILABLE"
EVAL_INVALID_RESPONSE = "INVALID_RESPONSE"
EVAL_API_ERROR = "API_ERROR"

GOLDEN_OCR_SAMPLE = r"4L-Y12@\X100C/C"
GOLDEN_B97A_BEAM = "B97A"
