"""
P2.6.10-C.4 — Shadow Truth Reconciliation & Vision Benchmark Calibration.
MODEL_VERSION: 10.11.17

SHADOW ONLY. Consumes C.3 six-beam artefacts. No Claude. No DXF. No production.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.17"
PHASE_ID = "P2.6.10-C.4"
PHASE_NAME = "Shadow Truth Reconciliation & Vision Benchmark Calibration"
OUTPUT_DIRNAME = "PhaseP2610C4_shadow_truth_reconciliation_benchmark_calibration"
GATE_VERSION = "P2610C4_SHADOW_TRUTH_RECONCILIATION_V1_0"

PRODUCTION_WRITE = False
SHADOW_ONLY = True
PRODUCTION_ACTION = "NO_CHANGE"
ENGINEERING_CHANGES = "NONE"
LIVE_CLAUDE_CALL = False

MODE_OFFLINE = "OFFLINE_RECONCILIATION"

P2610C3_OUTPUT_DIRNAME = "PhaseP2610C3_visual_completeness_claude_shadow"
P2610C1C2_OUTPUT_DIRNAME = "PhaseP2610C1C2_evidence_inventory_candidate_selection"
P269_OUTPUT_DIRNAME = "PhaseP269_reinforcement_group_interpretation"
C3_SIX_BEAM_NAME = "six_beam_benchmark.json"

STATUS_DET_CONFIRMED = "DETERMINISTIC_CONFIRMED"
STATUS_VIS_CONFIRMED = "VISION_CONFIRMED"
STATUS_EQUIVALENT = "BOTH_EQUIVALENT"
STATUS_AMBIGUOUS = "AMBIGUOUS_EVIDENCE"
STATUS_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"

SOURCE_DET = "DETERMINISTIC_R1"
SOURCE_P269 = "P269_EXPECTATION"
SOURCE_VISION = "VISION_CLAUDE"
SOURCE_SKETCH = "PHASE_SKETCH"
SOURCE_RENDER = "VISUAL_RENDER"
SOURCE_MANUAL = "MANUAL_VERIFICATION"

AVAIL_AVAILABLE = "AVAILABLE"
AVAIL_MISSING = "MISSING"

STRENGTH_STRONG = "STRONG"
STRENGTH_MODERATE = "MODERATE"
STRENGTH_LIMITED = "LIMITED"
STRENGTH_INSUFFICIENT = "INSUFFICIENT"

DECISION_VISION = "VISION_SIGNAL_SUPPORTED"
DECISION_DET = "DETERMINISTIC_SIGNAL_SUPPORTED"
DECISION_MIXED = "MIXED_SIGNAL"
DECISION_INSUFFICIENT = "INSUFFICIENT_EVIDENCE"
