"""
Create Version10 from frozen Version9 — lean accuracy-development fork.

Copies engineering code + input data. Excludes regenerated outputs / web_runs.
Also writes Version9/VERSION_FREEZE.md when --freeze-v9 is set (default).
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V9 = ROOT / "Version9"
V10 = ROOT / "Version10"

# Top-level trees / files relative to Version9
COPY_TREES = (
    "src",
    "Run_PY",
    "config",
    "schemas",
    "prompts",
)

COPY_FILES = (
    "requirements.txt",
    ".gitignore",
    "PIPELINE.md",
)

# data/ inputs only (not output / web_runs)
DATA_TREES = (
    "data/Benchmark_Set_2",
    "data/Benchmark_Set_3",
    "data/Excel_Presentation_Format",
    "data/framing",
    "data/general_notes",
)

WEBAPP_KEEP = (
    "app.py",
    "config.py",
    "routes.py",
    "requirements.txt",
    "README.md",
    ".gitignore",
    "services",
    "static",
    "templates",
)

IGNORE = shutil.ignore_patterns(
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
    "*.log",
    ".DS_Store",
    "Thumbs.db",
)


def _copy_tree(rel: str) -> None:
    src = V9 / rel
    dst = V10 / rel
    if not src.exists():
        print(f"  SKIP missing: {rel}")
        return
    if dst.exists():
        shutil.rmtree(dst)
    print(f"  copy tree {rel}")
    shutil.copytree(src, dst, ignore=IGNORE)


def _copy_file(rel: str) -> None:
    src = V9 / rel
    dst = V10 / rel
    if not src.exists():
        print(f"  SKIP missing: {rel}")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    print(f"  copy file {rel}")
    shutil.copy2(src, dst)


def _copy_webapp() -> None:
    src_root = V9 / "webapp"
    dst_root = V10 / "webapp"
    if dst_root.exists():
        shutil.rmtree(dst_root)
    dst_root.mkdir(parents=True)
    for name in WEBAPP_KEEP:
        src = src_root / name
        if not src.exists():
            print(f"  SKIP webapp/{name}")
            continue
        dst = dst_root / name
        if src.is_dir():
            print(f"  copy tree webapp/{name}")
            shutil.copytree(src, dst, ignore=IGNORE)
        else:
            print(f"  copy file webapp/{name}")
            shutil.copy2(src, dst)
    for sub in ("logs", "uploads", "outputs"):
        (dst_root / sub).mkdir(parents=True, exist_ok=True)
        (dst_root / sub / ".gitkeep").write_text("", encoding="utf-8")


def _ensure_empty_data_slots() -> None:
    for rel in (
        "data/output",
        "data/web_runs",
        "data/vision_dataset",
    ):
        d = V10 / rel
        d.mkdir(parents=True, exist_ok=True)
        (d / ".gitkeep").write_text("", encoding="utf-8")
        print(f"  empty slot {rel}/")


def write_v10_readme() -> None:
    text = """# Steel Beam Estimator — Version 10

**Active development branch.** Forked from frozen **Version 9** (accuracy baseline through QA.2B.2 / MODEL_VERSION **9.6.2**).

**Purpose:** Continue estimation accuracy and pipeline improvements without
changing the frozen Version 9 tree.

**Starting baseline:** engineering parity with `Version9/` at freeze time.
Bump MODEL_VERSION as new Version10 phases land (recommended first milestone: **10.0.0**).

**Version 9 is frozen.** Do not add features there. See `Version9/VERSION_FREEZE.md`.

---

## What was copied from Version 9

| Area | Included |
|------|----------|
| `src/` | All engineering + QA packages (through T1.8.3.1 / QA.2B.2) |
| `Run_PY/` | Production + Track1 + QA runners |
| `config/`, `schemas/`, `prompts/` | Yes |
| `webapp/` | App code only |
| `data/Benchmark_Set_*`, framing, general_notes, Excel template | Input drawing sets |
| `requirements.txt`, `.gitignore`, `PIPELINE.md` | Yes |

## Intentionally excluded

| Area | Reason |
|------|--------|
| `data/output/**` | Regenerated by runners |
| `data/web_runs/**` | Per-run web artefacts |
| `Cursor_Explanation/` | Local notes |
| `__pycache__` / `.pytest_cache` | Generated |

---

## Setup

```powershell
pip install -r requirements.txt
cd Version10
$env:PYTHONPATH="src"
```

## Quick start

```powershell
cd Version10
python Run_PY/run_phase_vroot1_dynamic_pipeline_initialization.py
```

Outputs: `Version10/data/output/` (offline) or `Version10/data/web_runs/<run_id>/` (web).

## Web app

```powershell
cd Version10\\webapp
python app.py
```

Production Lightsail packaging may still reference a certified baseline
(`Version8` / later promoted engines). Version10 is the active accuracy tree.
"""
    (V10 / "README.md").write_text(text, encoding="utf-8")
    print("  wrote Version10/README.md")


def write_v9_freeze() -> None:
    text = """# Version 9 — FROZEN

**Status:** FROZEN as of 2026-08-06  
**Final MODEL_VERSION range:** 9.0.x → **9.6.2** (QA.2B.2 accuracy report)  
**Successor:** `Version10/`

## Do not continue feature work here

All new development — including further accuracy, ownership, rendering, and
benchmark improvements — continues in **Version10**.

Version 9 remains the completed accuracy branch that delivered:

- Track 1 geometric stirrup evidence (T1) + OpenCV crops
- Entity / annotation / beam ownership (T1.6–T1.8)
- Adaptive render extent (T1.8.2)
- Shared engineering ownership + scope dedup (T1.8.3 / T1.8.3.1)
- QA.2B.0 pipeline integration
- QA.2B.1 production regeneration + ground-truth re-benchmark
- QA.2B.2 Overall Accuracy Report (V9.6.1)

Do not change engineering behaviour in this tree.

## What shipped into Version 10

Lean copy for continued accuracy work:

- `src/`, `Run_PY/`, `config/`, `schemas/`, `prompts/`
- `webapp/` (code only)
- `data/` input drawing sets + Excel template
- `requirements.txt`, `PIPELINE.md`, `.gitignore`

**Not carried forward:** `data/output/**`, `data/web_runs/**`,
`Cursor_Explanation/`, local webapp `logs/` / `uploads/` / `outputs/`.

## Reference artefacts (historical, under Version9)

- `data/output/PhaseQA2B1_production_regeneration/` — regenerated GT benchmark
- `data/output/PhaseQA2B2_accuracy_report/Overall_Accuracy_Report_V9.6.1.docx`
"""
    (V9 / "VERSION_FREEZE.md").write_text(text, encoding="utf-8")
    print("  wrote Version9/VERSION_FREEZE.md")


def patch_v9_readme() -> None:
    readme = V9 / "README.md"
    if not readme.exists():
        return
    banner = (
        "> **FROZEN.** Do **not** add features here. Continue work in "
        "**`Version10/`**. See `VERSION_FREEZE.md`.\n\n"
    )
    text = readme.read_text(encoding="utf-8")
    if "FROZEN" in text[:400] and "Version10" in text[:400]:
        print("  Version9/README.md already marked frozen")
        return
    # Replace active-development lead
    text = text.replace(
        "**Active development branch.** Forked from frozen **Version 8** (`v8.9.5`).",
        "**FROZEN.** Successor is **Version10**. Originally forked from frozen **Version 8** (`v8.9.5`).",
    )
    if not text.startswith(">"):
        text = banner + text
    readme.write_text(text, encoding="utf-8")
    print("  patched Version9/README.md")


def patch_v10_pipeline() -> None:
    path = V10 / "PIPELINE.md"
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    text = text.replace("Version9", "Version10")
    path.write_text(text, encoding="utf-8")
    print("  patched Version10/PIPELINE.md (Version9 -> Version10)")


def patch_sbe_readme() -> None:
    path = ROOT / "Steel-Beam-Estimation" / "README.md"
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    old = "| **Version9** | Accuracy: reinforcement ID & interpretation | **Active** |"
    new = (
        "| **Version9** | Accuracy through QA.2B.2 (9.6.2) | **Frozen** |\n"
        "| **Version10** | Continued accuracy / ownership / pipeline work | **Active** |"
    )
    if "| **Version10** |" in text:
        print("  Steel-Beam-Estimation/README.md already has Version10")
        return
    if old in text:
        text = text.replace(old, new)
        path.write_text(text, encoding="utf-8")
        print("  patched Steel-Beam-Estimation/README.md")
    else:
        print("  WARN: Version9 active row not found in Steel-Beam-Estimation/README.md")


def patch_v8_freeze_note() -> None:
    """Leave V8 freeze pointing at V9 historically; add note about V10."""
    path = V8 = ROOT / "Version8" / "VERSION_FREEZE.md"
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    note = (
        "\n## Later successor\n\n"
        "Accuracy work moved from Version9 to **Version10** (2026-08-06). "
        "Version8 remains the certified production baseline; Version9 remains "
        "the completed 9.x accuracy branch.\n"
    )
    if "Version10" in text:
        print("  Version8/VERSION_FREEZE.md already mentions Version10")
        return
    path.write_text(text.rstrip() + "\n" + note, encoding="utf-8")
    print("  annotated Version8/VERSION_FREEZE.md")


def main() -> int:
    ap = argparse.ArgumentParser(description="Create Version10 from Version9")
    ap.add_argument(
        "--no-freeze-v9",
        action="store_true",
        help="Do not write Version9 freeze markers",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing Version10 directory",
    )
    args = ap.parse_args()

    if not V9.exists():
        raise SystemExit(f"Version9 not found: {V9}")

    if V10.exists():
        if not args.force:
            raise SystemExit(
                f"Version10 already exists: {V10}\nRe-run with --force to replace."
            )
        print(f"Removing existing {V10} ...")
        shutil.rmtree(V10)

    print(f"Creating {V10} from {V9} ...")
    V10.mkdir(parents=True)

    for rel in COPY_TREES:
        _copy_tree(rel)
    for rel in COPY_FILES:
        _copy_file(rel)
    for rel in DATA_TREES:
        _copy_tree(rel)
    _copy_webapp()
    _ensure_empty_data_slots()
    write_v10_readme()
    patch_v10_pipeline()

    if not args.no_freeze_v9:
        write_v9_freeze()
        patch_v9_readme()
        patch_sbe_readme()
        patch_v8_freeze_note()

    print("\nDone.")
    print(f"  Active tree : {V10}")
    print(f"  Frozen tree : {V9}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
