"""
Phase P2.6.6 — Semantic Longitudinal Ambiguity Resolver.
MODEL_VERSION: 10.11.6

Shadow / research only. Does not change P2.6.4 or P2.6.5 routing.
No engineering recompute. No production insert.
"""
from __future__ import annotations

MODEL_VERSION = "10.11.6"
PHASE_ID = "P2.6.6"
PHASE_NAME = "Semantic Longitudinal Ambiguity Resolver"
OUTPUT_DIRNAME = "PhaseP266_semantic_longitudinal_resolver"
SCOPE = "ROLE_COVERAGE_GAP_SEMANTIC_SHADOW"
MODE = "SHADOW_RESEARCH"
ENGINEERING_CHANGES = "NONE"

GATE_VERSION = "P266_SEMANTIC_LONGITUDINAL_RESOLVER_V1_0"
P264_GATE_VERSION = "P264_SELECTIVE_ROLE_GAP_GATE_V1_0"
P265_GATE_VERSION = "P265_SPATIAL_CONTEXT_LONGITUDINAL_V1_0"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

SAMPLE_SEED = 2611101
FROZEN_SAMPLE_BEAMS = 75
MAX_LIVE_CALLS_REPLAY = 0

MODE_REPLAY = "REPLAY_P261_CACHED"
MODE_LIVE = "LIVE_API"

P261_OUTPUT_DIRNAME = "PhaseP261_stratified_vision_candidate_recovery"
P264_OUTPUT_DIRNAME = "PhaseP264_selective_role_gap_gate"
P265_OUTPUT_DIRNAME = "PhaseP265_spatial_context_longitudinal"

PROMPT_VERSION = "P266_SEMANTIC_LONGITUDINAL_RESOLVER_PROMPT_V1"
SCHEMA_VERSION = "P266_SEMANTIC_LONGITUDINAL_SCHEMA_V1"
ADAPTER_SOURCE = "REPLAY_P261_OBSERVATION_ADAPTER"

DECISION_CALL = "CALL_VISION"
DECISION_SKIP = "SKIP_VISION"
DECISION_HOLD = "HOLD"

COVER_FULL = "FULLY_COVERED"
COVER_LAYER = "ROLE_COVERAGE_GAP"

SEM_DISTINCT = "DISTINCT_REINFORCEMENT"
SEM_DUPLICATE = "DUPLICATE_OR_REPEAT"
SEM_AMBIGUOUS = "AMBIGUOUS"
SEM_UNSUPPORTED = "UNSUPPORTED"

SHADOW_DISTINCT = "SHADOW_DISTINCT"
SHADOW_DUPLICATE = "SHADOW_DUPLICATE"
SHADOW_AMBIGUOUS = "SHADOW_AMBIGUOUS"
SHADOW_UNSUPPORTED = "SHADOW_UNSUPPORTED"

LAYER_TOP = "TOP"
LAYER_BOTTOM = "BOTTOM"
LAYER_SIDE = "SIDE"
LAYER_UNKNOWN = "UNKNOWN"

REP_REPRESENTED = "REPRESENTED"
REP_NOT_REPRESENTED = "NOT_REPRESENTED"
REP_UNCERTAIN = "UNCERTAIN"

CONFIDENCE_SKIP_THRESHOLD = 0.60
ADAPTER_DISTINCT_CONFIDENCE = 0.72
ADAPTER_DUPLICATE_CONFIDENCE = 0.72
ADAPTER_AMBIGUOUS_CONFIDENCE = 0.40
ADAPTER_UNSUPPORTED_CONFIDENCE = 0.20

STATUS_SKIP = "CONTEXT_SUPPORTS_SKIP"
STATUS_CALL = "CONTEXT_SUPPORTS_CALL"
STATUS_AMBIGUOUS = "CONTEXT_AMBIGUOUS"
STATUS_INSUFFICIENT = "CONTEXT_INSUFFICIENT"

DET_ALREADY = "ALREADY_DETECTED"
DET_MISSING = "POTENTIALLY_MISSING"
DET_CONFLICT = "CONFLICTING"

ALLOWED_DECISIONS = (SEM_DISTINCT, SEM_DUPLICATE, SEM_AMBIGUOUS, SEM_UNSUPPORTED)
ALLOWED_LAYERS = (LAYER_TOP, LAYER_BOTTOM, LAYER_SIDE, LAYER_UNKNOWN)
ALLOWED_REPRESENTATION = (REP_REPRESENTED, REP_NOT_REPRESENTED, REP_UNCERTAIN)

DISTINCT_REASON_CODES = (
    "DISTINCT_LAYER",
    "DISTINCT_CALLOUT_TARGET",
    "UNREPRESENTED_REINFORCEMENT",
    "SEPARATE_REINFORCEMENT_REGION",
    "SEPARATE_REPEATED_SPEC",
    "EXPLICIT_BOTTOM_WHILE_TOP_ONLY",
    "EXPLICIT_TOP_WHILE_BOTTOM_ONLY",
)
DUPLICATE_REASON_CODES = (
    "SAME_REINFORCEMENT_TARGET",
    "REPEATED_CALLOUT",
    "CONTINUATION_OF_EXISTING_SPEC",
    "ALREADY_REPRESENTED_LAYER",
    "DUPLICATE_ANNOTATION",
    "SAME_REINFORCEMENT_CONFIGURATION",
)
AMBIGUOUS_REASON_CODES = (
    "CROSS_LAYER_AMBIGUITY",
    "LEADER_TARGET_UNCLEAR",
    "REPEATED_CALLOUT_AMBIGUITY",
    "MULTIPLE_PLAUSIBLE_TARGETS",
    "INSUFFICIENT_VISUAL_SEPARATION",
    "DETERMINISTIC_VISION_CONFLICT",
)
UNSUPPORTED_REASON_CODES = (
    "IMAGE_INSUFFICIENT",
    "CALLOUT_NOT_VISIBLE",
    "LEADER_NOT_VISIBLE",
    "BEAM_CONTEXT_INSUFFICIENT",
    "OCR_UNREADABLE",
)
ALLOWED_REASON_CODES = (
    DISTINCT_REASON_CODES
    + DUPLICATE_REASON_CODES
    + AMBIGUOUS_REASON_CODES
    + UNSUPPORTED_REASON_CODES
)
