"""
Phase P2.5.9 — Beam-Safe Arbitration.
MODEL_VERSION: 10.8.5

Compares three Vision promotion strategies in isolated shadow recomputes.
Runtime arbitration must not read estimator/ground-truth steel.
Maximum promotion level remains CONTROLLED_RECOMPUTE. Production is untouched.
"""
from __future__ import annotations

MODEL_VERSION = "10.8.5"
PHASE_ID = "P2.5.9"
PHASE_NAME = "Beam-Safe Arbitration"
OUTPUT_DIRNAME = "PhaseP259_beam_safe_arbitration"
SCOPE = "FIFTH_SET_PRIMARY"
MODE = "REPLAY_P257_LIVE_RESULTS"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "REPLAY_ONLY"
MAX_PROMOTION_LEVEL = "CONTROLLED_RECOMPUTE"
PRODUCTION_WRITE = False

STRATEGY_P258_CURRENT = "P258_CURRENT"
STRATEGY_UNKNOWN_ONLY = "P259_UNKNOWN_ONLY"
STRATEGY_CONSERVATIVE_PARTIAL = "P259_CONSERVATIVE_PARTIAL"
STRATEGIES = (
    STRATEGY_P258_CURRENT,
    STRATEGY_UNKNOWN_ONLY,
    STRATEGY_CONSERVATIVE_PARTIAL,
)

OUT_ACCEPT_UNKNOWN = "ACCEPT_UNKNOWN_RECOVERY"
OUT_ACCEPT_PARTIAL = "ACCEPT_CONSERVATIVE_PARTIAL"
OUT_HOLD_PARTIAL = "HOLD_PARTIAL"
OUT_REJECT_PARTIAL = "REJECT_PARTIAL"
OUT_BLOCKED_CONFIRMED = "BLOCKED_CONFIRMED_FIELD"
OUT_INELIGIBLE = "PRODUCTION_INELIGIBLE"
OUT_BLOCKED = "BLOCKED"

REASON_UNKNOWN_VALID = "DETERMINISTIC_UNKNOWN_VISION_VALID"
REASON_CONFIRMED = "CONFIRMED_FIELD_CANNOT_BE_OVERRIDDEN"
REASON_PARTIAL_NEEDS_ARB = "PARTIAL_REPAIR_REQUIRES_ARBITRATION"
REASON_PARTIAL_EXPANDS = "PARTIAL_REPAIR_EXPANDS_SPACING_PATTERN"
REASON_PARTIAL_SEGMENTATION = "PARTIAL_REPAIR_INCREASES_PIECE_SEGMENTATION"
REASON_PARTIAL_PIECE_COUNT = "PARTIAL_REPAIR_INCREASES_PIECE_COUNT"
REASON_PARTIAL_LOW_CONF = "PARTIAL_REPAIR_LOW_ENGINEERING_CONFIDENCE"
REASON_ARB_HOLD = "ARBITRATION_HOLD"
REASON_ARB_ACCEPTED = "ARBITRATION_ACCEPTED"
REASON_EXISTING_STIRRUP = "PARTIAL_REPAIR_BEAM_HAS_DETERMINISTIC_STIRRUP"
REASON_ZONE_TRUNCATED = "PARTIAL_REPAIR_EXISTING_ZONE_TRUNCATED_LABEL"

PRIMARY_DRAWING_SET = "Fifth Set Drawings"
PRIMARY_SET_KEY = "Fifth"
P257_OUTPUT = "PhaseP257_unseen_drawing_controlled_vision_validation"
P258_OUTPUT = "PhaseP258_controlled_vision_field_repair"
