"""
BBS Completion Engine — Phase V.B.1 MODULE 3
Updated: Phase SI.1 integration (MODEL_VERSION 6.6.1)

Generates full estimator-style Bar Bending Schedule rows from L.2 data + steel weights.
Each beam contains rows for all bar roles per specification.
Every engineering object appears as its own row.

STIRRUP rows are now generated by Phase SI.1 StirrupImprover, which correctly
splits variable-spacing stirrups into engineering shear zones and merges
identical support zones into single estimator-style BBS rows.
"""
import math
import sys
import pathlib
from typing import List, Dict, Any, Optional, Tuple

from production_output_models import BBSRow, BeamSteelWeight, ProjectSteelSummary

# ── SI.1 integration ─────────────────────────────────────────────────────────
_SI1_SRC = pathlib.Path(__file__).parents[1] / "PhaseSI.1_stirrup_improvement"
if str(_SI1_SRC) not in sys.path:
    sys.path.insert(0, str(_SI1_SRC))

try:
    from phase_si1_orchestrator import StirrupImprover
    _STIRRUP_IMPROVER = StirrupImprover()
    _SI1_AVAILABLE = True
except Exception:
    _STIRRUP_IMPROVER = None
    _SI1_AVAILABLE = False

_FRAME_UNRESOLVED = "UNRESOLVED"

_ROLE_DISPLAY = {
    "TOP_MAIN":    "Top bars",
    "BOTTOM_MAIN": "Bottom bars",
    "TOP_EXTRA":   "Top bars - Extra",
    "BOTTOM_EXTRA":"Bottom bars - Extra",
    "SIDE_FACE":   "SFR",
    "STIRRUP":     "Stirrups",
    "SPACER":      "Spacer bars",
    "BENT":        "Bent bars",
    "CRANKED":     "Cranked bars",
    "DEVELOPMENT": "Dev. length bars",
    "LAP":         "Lap bars",
}

_SUPPORTED_DIAMETERS = [8, 10, 12, 16, 20, 25, 32]


class BBSCompletionEngine:
    """
    Converts ProjectSteelSummary into a flat list of BBSRow objects that
    mirror the estimator workbook layout.
    """

    def __init__(self, summary: ProjectSteelSummary, frame_type: Optional[str] = None) -> None:
        self.summary = summary
        resolved = (frame_type or "").strip()
        if resolved and resolved not in ("UNKNOWN_FLOOR", "UNKNOWN"):
            self._frame_type = resolved
        else:
            self._frame_type = _FRAME_UNRESOLVED

    def generate(self) -> List[BBSRow]:
        rows: List[BBSRow] = []
        si = 1
        for bw in self.summary.beam_weights:
            # ── Beam header row ──────────────────────────────────────
            rows.append(BBSRow(
                si_no=si,
                frame_type=self._frame_type,
                description=bw.beam_id,
                diameter_mm=1,                    # member count
                spacing_m=round(bw.span_mm / 1000, 3) if bw.span_mm else None,
                quantity=int(bw.width_mm) if bw.width_mm else None,
                dvlp_length_m=bw.depth_mm / 1000 if bw.depth_mm else None,
                cut_length_m=None,
                total_length_m=None,
                total_weight_kg=bw.total_weight_kg,
                is_beam_header=True,
                beam_id=bw.beam_id,
            ))
            si += 1

            # Group bars by role to produce one row per bar group
            role_groups: Dict[str, List[Any]] = {}
            for bar in bw.bar_weights:
                role_groups.setdefault(bar.role, []).append(bar)

            role_order = [
                "TOP_MAIN", "TOP_EXTRA", "BOTTOM_MAIN", "BOTTOM_EXTRA",
                "SIDE_FACE", "STIRRUP", "SPACER", "BENT", "CRANKED",
                "DEVELOPMENT", "LAP",
            ]

            for role in role_order:
                bars = role_groups.get(role, [])
                if role == "SPACER":
                    bars = self._aggregate_equivalent_spacers(bars)
                for bar in bars:
                    # ── SI.1: STIRRUP role handled by StirrupImprover ────────
                    if role == "STIRRUP" and _SI1_AVAILABLE and _STIRRUP_IMPROVER is not None:
                        si1_rows = _STIRRUP_IMPROVER.compute_beam(
                            bar=bar.__dict__,
                            beam_id=bw.beam_id,
                            span_mm=bw.span_mm,
                            depth_mm=bw.depth_mm,
                            width_mm=bw.width_mm,
                        )
                        for rd in si1_rows:
                            rows.append(BBSRow(**rd))
                        continue
                    # ── All other roles: original V.B.1 logic ───────────────
                    dw: Dict[int, Optional[float]] = {d: None for d in _SUPPORTED_DIAMETERS}
                    d_key = int(bar.diameter_mm)
                    if d_key in dw:
                        dw[d_key] = round(bar.total_weight_kg, 3)

                    spacing_m: Optional[float] = None
                    if bar.role == "SIDE_FACE" and bar.cut_length_mm:
                        if bw.span_mm and bar.quantity and bar.quantity > 1:
                            spacing_m = round(bw.span_mm / (bar.quantity * 1000), 3)

                    rows.append(BBSRow(
                        si_no=None,
                        frame_type=self._frame_type,
                        description=_ROLE_DISPLAY.get(role, role),
                        diameter_mm=bar.diameter_mm,
                        spacing_m=spacing_m,
                        quantity=bar.quantity,
                        dvlp_length_m=round(
                            bar.cut_length_mm / 1000 - bw.span_mm / 1000, 3
                        ) if bar.cut_length_mm and bw.span_mm else None,
                        cut_length_m=round(bar.cut_length_mm / 1000, 3),
                        total_length_m=round(
                            bar.cut_length_mm * bar.quantity / 1000, 3
                        ),
                        weight_d8=dw[8],
                        weight_d10=dw[10],
                        weight_d12=dw[12],
                        weight_d16=dw[16],
                        weight_d20=dw[20],
                        weight_d25=dw[25],
                        weight_d32=dw[32],
                        total_weight_kg=round(bar.total_weight_kg, 3),
                        is_beam_header=False,
                        beam_id=bw.beam_id,
                    ))

        for row in rows:
            row.frame_type = self._frame_type
        return rows

    @staticmethod
    def _aggregate_equivalent_spacers(bars: List[Any]) -> List[Any]:
        """One BBS line per identical spacer spec (dia + cut) on the beam.

        LEFT/RIGHT zones are calculated separately in M.2; equivalent outputs
        combine here. Does not merge different diameters or cut lengths.
        """
        if len(bars) <= 1:
            return bars
        grouped: Dict[Tuple, Any] = {}
        order: List[Tuple] = []
        for bar in bars:
            key = (
                int(round(float(bar.diameter_mm))),
                round(float(bar.cut_length_mm or 0.0), 3),
            )
            if key not in grouped:
                grouped[key] = bar
                order.append(key)
                continue
            prev = grouped[key]
            qty = int(prev.quantity or 0) + int(bar.quantity or 0)
            total_w = float(prev.total_weight_kg or 0.0) + float(bar.total_weight_kg or 0.0)
            grouped[key] = type(prev)(
                bar_id=str(prev.bar_id),
                beam_id=prev.beam_id,
                role=prev.role,
                bar_label=prev.bar_label,
                diameter_mm=prev.diameter_mm,
                quantity=qty,
                steel_grade=prev.steel_grade,
                cut_length_mm=prev.cut_length_mm,
                cut_length_source=prev.cut_length_source,
                area_mm2=prev.area_mm2,
                weight_per_bar_kg=prev.weight_per_bar_kg,
                total_weight_kg=total_w,
                formula_used=prev.formula_used + "|aggregated_equivalent_spacer_zones",
            )
        return [grouped[k] for k in order]

    def diameter_totals(self, rows: List[BBSRow]) -> Dict[int, float]:
        totals: Dict[int, float] = {d: 0.0 for d in _SUPPORTED_DIAMETERS}
        for row in rows:
            if not row.is_beam_header:
                for d, attr in [
                    (8, "weight_d8"), (10, "weight_d10"), (12, "weight_d12"),
                    (16, "weight_d16"), (20, "weight_d20"), (25, "weight_d25"),
                    (32, "weight_d32"),
                ]:
                    val = getattr(row, attr, None)
                    if val:
                        totals[d] += val
        return totals
