"""G.5.1 engineering object type constants — instantiated reinforcement classes."""

from __future__ import annotations

from typing import FrozenSet

OBJECT_TYPE_TOP_BAR = "TOP_BAR"
OBJECT_TYPE_TOP_EXTRA_BAR = "TOP_EXTRA_BAR"
OBJECT_TYPE_BOTTOM_BAR = "BOTTOM_BAR"
OBJECT_TYPE_BOTTOM_EXTRA_BAR = "BOTTOM_EXTRA_BAR"
OBJECT_TYPE_SIDE_FACE_REINFORCEMENT = "SIDE_FACE_REINFORCEMENT"
OBJECT_TYPE_STIRRUP = "STIRRUP"
OBJECT_TYPE_SPACER_BAR = "SPACER_BAR"
OBJECT_TYPE_DEVELOPMENT_LENGTH = "DEVELOPMENT_LENGTH"
OBJECT_TYPE_HOOK = "HOOK"
OBJECT_TYPE_ANCHORAGE = "ANCHORAGE"
OBJECT_TYPE_REINFORCEMENT_NOTE = "REINFORCEMENT_NOTE"
OBJECT_TYPE_DIMENSION = "DIMENSION"
OBJECT_TYPE_BEAM_LABEL = "BEAM_LABEL"
OBJECT_TYPE_UNKNOWN = "UNKNOWN"

G51_OBJECT_TYPES: FrozenSet[str] = frozenset({
    OBJECT_TYPE_TOP_BAR,
    OBJECT_TYPE_TOP_EXTRA_BAR,
    OBJECT_TYPE_BOTTOM_BAR,
    OBJECT_TYPE_BOTTOM_EXTRA_BAR,
    OBJECT_TYPE_SIDE_FACE_REINFORCEMENT,
    OBJECT_TYPE_STIRRUP,
    OBJECT_TYPE_SPACER_BAR,
    OBJECT_TYPE_DEVELOPMENT_LENGTH,
    OBJECT_TYPE_HOOK,
    OBJECT_TYPE_ANCHORAGE,
    OBJECT_TYPE_REINFORCEMENT_NOTE,
    OBJECT_TYPE_DIMENSION,
    OBJECT_TYPE_BEAM_LABEL,
    OBJECT_TYPE_UNKNOWN,
})

CLASSIFICATION_SOURCE_GEOMETRY = "GEOMETRY"
CLASSIFICATION_SOURCE_TEXT = "TEXT"
CLASSIFICATION_SOURCE_GEOMETRY_AND_TEXT = "GEOMETRY_AND_TEXT"
CLASSIFICATION_SOURCE_LEADER = "LEADER"
CLASSIFICATION_SOURCE_LEADER = "LEADER"
CLASSIFICATION_SOURCE_INFERRED = "INFERRED"
