"""
Phase P2.5.7 — Unseen-Drawing Controlled Vision Validation.
MODEL_VERSION: 10.8.3

UNSEEN Fifth Set + LIVE Claude + P2.5.6 field validation + independent GT.
Shadow observer only. Deterministic P2.5.1 remains production authority.
"""
from __future__ import annotations

MODEL_VERSION = "10.8.3"
PHASE_ID = "P2.5.7"
PHASE_NAME = "Unseen-Drawing Controlled Vision Validation"
OUTPUT_DIRNAME = "PhaseP257_unseen_drawing_controlled_vision_validation"
SCOPE = "FIFTH_SET_UNSEEN_ONLY"
MODE = "SELECTIVE_LIVE_SHADOW"
ENGINEERING_CHANGES = "NONE"
CLAUDE = "SHADOW_OBSERVER"
PRIMARY_SET_KEY = "Fifth"
PRIMARY_DRAWING_SET = "Fifth Set Drawings"
BANNED_PRIMARY_SETS = ("Fourth",)  # used by P2.5.4/5/6 Claude vision

PROMPT_VERSION = "P254_SEMANTIC_VISION_PROMPT_V1"
SCHEMA_VERSION = "P254_SEMANTIC_INTERPRETATION_SCHEMA_V1"
CLAUDE_MODEL = "claude-sonnet-4-5"
TEMPERATURE = 0

SHADOW_OBJECT_KIND = "UnseenFieldValidationResult"
PRODUCTION_WRITE = False
ZONE_PROMOTABLE = False

EVAL_EXACT = "EXACT"
EVAL_PARTIAL = "PARTIAL"
EVAL_WRONG = "WRONG"
EVAL_UNRESOLVED = "UNRESOLVED"
EVAL_NOT_SCORED = "NOT_SCORED"
EVAL_NOT_APPLICABLE = "NOT_APPLICABLE"

INC_ADDS_CORRECT = "VISION_ADDS_CORRECT_FIELD"
INC_CONFIRMS = "VISION_CONFIRMS_DETERMINISTIC"
INC_CONFLICTS_CORRECT_DET = "VISION_CONFLICTS_WITH_CORRECT_DETERMINISTIC"
INC_CORRECTS_WRONG_DET = "VISION_CORRECTS_WRONG_DETERMINISTIC"
INC_WRONG_ON_CORRECT_DET = "VISION_WRONG_ON_CORRECT_DETERMINISTIC"
INC_NONE = "NO_INCREMENTAL_VALUE"
INC_NOT_SCORED = "NOT_SCORED"
