"""
beam_loss_detector.py — Classifies and explains every beam loss.
MODEL_VERSION: 7.1.2  |  READ-ONLY
"""

from __future__ import annotations
import json
import pathlib
from typing import Dict, List, Optional

from .engineering_trace_models import (
    BeamLifecycle, LossCategory, LostBeam, StageSnapshot
)

WORKSPACE = pathlib.Path(r"C:\Users\nishanth.h\SteelBeamEstimator")

# Known stale-output patterns — stage outputs that were generated from a
# DIFFERENT dataset than what is currently in V.ROOT.1
_STALE_MODEL_VERSIONS = {"6.4.0", "6.4.1", "6.5.0", "6.6.0", "6.6.1", "6.6.2", "6.6.3"}
_BENCHMARK1_BEAM_IDS  = {f"B{i}" for i in range(1, 19)}  # B1-B18 (Benchmark Set 1)


class BeamLossDetector:
    """
    Inspects stage comparisons and lifecycle data to classify every lost beam.
    """

    def __init__(self, stage_order: List[str], snapshots: Dict[str, StageSnapshot]):
        self._stage_order = stage_order
        self._snapshots   = snapshots

    def detect(
        self,
        lifecycles: Dict[str, BeamLifecycle],
    ) -> List[LostBeam]:
        lost: List[LostBeam] = []

        for beam_id, lc in lifecycles.items():
            if lc.lost_at is None and lc.last_seen is None:
                # Beam never appeared at any stage
                lc.loss_category = LossCategory.NOT_CREATED
                lc.loss_reason   = (
                    "Beam discovered by V.ROOT.1 but never appeared in any "
                    "downstream stage output artefact."
                )
                lost.append(LostBeam(
                    beam_id          = beam_id,
                    last_valid_stage = "NONE",
                    first_lost_stage = self._stage_order[0] if self._stage_order else "UNKNOWN",
                    loss_category    = LossCategory.NOT_CREATED,
                    loss_reason      = lc.loss_reason,
                    confidence       = "HIGH",
                ))
            elif lc.lost_at is not None:
                category, reason, confidence = self._classify(
                    beam_id, lc.last_seen, lc.lost_at
                )
                lc.loss_category = category
                lc.loss_reason   = reason
                lost.append(LostBeam(
                    beam_id          = beam_id,
                    last_valid_stage = lc.last_seen or "UNKNOWN",
                    first_lost_stage = lc.lost_at,
                    loss_category    = category,
                    loss_reason      = reason,
                    confidence       = confidence,
                ))

        return lost

    def _classify(
        self,
        beam_id: str,
        last_valid: Optional[str],
        first_lost: str,
    ) -> tuple:
        lost_snap   = self._snapshots.get(first_lost)
        source_snap = self._snapshots.get("VROOT1")

        # Check if the losing stage has a known stale model version
        if lost_snap and lost_snap.raw_metadata:
            mv = lost_snap.raw_metadata.get("model_version", "")
            if mv in _STALE_MODEL_VERSIONS:
                reason = (
                    f"Stage '{first_lost}' output was generated by model_version "
                    f"'{mv}' against Benchmark Set 1 data and has NOT been "
                    f"re-executed since V.ROOT.1 populated the V5 adapter files "
                    f"with Benchmark Set 2 beams. This is a STALE_OUTPUT condition, "
                    f"not a processing error. Re-running {first_lost} against the "
                    f"current V5 adapter files (which now contain 65 Benchmark Set 2 "
                    f"beams) should recover this beam."
                )
                return LossCategory.STALE_OUTPUT, reason, "HIGH"

        # Check: beam present in all other stages after source but not in this one
        present_after = [
            s for s in self._stage_order
            if self._stage_order.index(s) > self._stage_order.index(first_lost)
            and beam_id in (self._snapshots.get(s) or StageSnapshot(
                stage_id="", stage_name="", beam_count=0, beam_ids=[],
                beam_uuids={}, input_files=[], output_file="",
                artefact_exists=False, timestamp=None, raw_metadata={})).beam_ids
        ]
        if present_after:
            reason = (
                f"Beam {beam_id} was absent at '{first_lost}' but reappeared "
                f"at later stages: {present_after}. Likely a filtering/ordering issue."
            )
            return LossCategory.FILTERED, reason, "MEDIUM"

        # Default: pipeline skipped
        reason = (
            f"Beam {beam_id} last appeared at '{last_valid}' and was absent "
            f"from '{first_lost}' onward. The downstream stage may not have been "
            f"re-executed after V.ROOT.1 updated the V5 adapter files."
        )
        return LossCategory.PIPELINE_SKIP, reason, "MEDIUM"
