"""Engineering Semantic Relationship type constants — Phase G.5.0.1."""

from __future__ import annotations

from typing import FrozenSet

REL_HAS_DIMENSION = "HAS_DIMENSION"
REL_HAS_LEADER = "HAS_LEADER"
REL_HAS_NOTE = "HAS_NOTE"
REL_HAS_SUPPORT_NOTE = "HAS_SUPPORT_NOTE"
REL_HAS_SIDE_FACE_NOTE = "HAS_SIDE_FACE_NOTE"
REL_HAS_STIRRUP_NOTE = "HAS_STIRRUP_NOTE"
REL_HAS_CALLOUT = "HAS_CALLOUT"
REL_HAS_SPACING_NOTE = "HAS_SPACING_NOTE"
REL_HAS_DEVELOPMENT_LENGTH = "HAS_DEVELOPMENT_LENGTH"
REL_ANNOTATES = "ANNOTATES"
REL_REFERENCES = "REFERENCES"
REL_CONNECTED_TO = "CONNECTED_TO"
REL_ASSOCIATED_WITH = "ASSOCIATED_WITH"
REL_PART_OF_GROUP = "PART_OF_GROUP"
REL_CONTINUES_TO = "CONTINUES_TO"
REL_UNKNOWN = "UNKNOWN"

VALID_SEMANTIC_RELATIONSHIP_TYPES: FrozenSet[str] = frozenset({
    REL_HAS_DIMENSION,
    REL_HAS_LEADER,
    REL_HAS_NOTE,
    REL_HAS_SUPPORT_NOTE,
    REL_HAS_SIDE_FACE_NOTE,
    REL_HAS_STIRRUP_NOTE,
    REL_HAS_CALLOUT,
    REL_HAS_SPACING_NOTE,
    REL_HAS_DEVELOPMENT_LENGTH,
    REL_ANNOTATES,
    REL_REFERENCES,
    REL_CONNECTED_TO,
    REL_ASSOCIATED_WITH,
    REL_PART_OF_GROUP,
    REL_CONTINUES_TO,
    REL_UNKNOWN,
})

CLASSIFICATION_SOURCE_PROXIMITY = "PROXIMITY"
CLASSIFICATION_SOURCE_LEADER_LINK = "LEADER_LINK"
CLASSIFICATION_SOURCE_GROUPING = "GROUPING"
CLASSIFICATION_SOURCE_CONTINUITY = "CONTINUITY"
CLASSIFICATION_SOURCE_ANNOTATION = "ANNOTATION"
CLASSIFICATION_SOURCE_INFERRED = "INFERRED"

STATE_DISCOVERED = "DISCOVERED"
STATE_CLASSIFIED = "CLASSIFIED"
STATE_VALIDATED = "VALIDATED"
STATE_CONSUMED = "CONSUMED"
STATE_FAILED = "FAILED"

VALID_RELATIONSHIP_LIFECYCLE: FrozenSet[str] = frozenset({
    STATE_DISCOVERED,
    STATE_CLASSIFIED,
    STATE_VALIDATED,
    STATE_CONSUMED,
    STATE_FAILED,
})

REINFORCEMENT_ROLE_TYPES = frozenset({
    "LONGITUDINAL_REINFORCEMENT_ROLE",
    "TRANSVERSE_REINFORCEMENT_ROLE",
    "SIDE_FACE_REINFORCEMENT_ROLE",
})
